// <auto-generated />
namespace GAPv3.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class CreateStatus_UpdateReportValueFK_statusId : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(CreateStatus_UpdateReportValueFK_statusId));
        
        string IMigrationMetadata.Id
        {
            get { return "201808091705552_CreateStatus_UpdateReportValue(FK_statusId)"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
