namespace GAPv3.Migrations
{
    using System;
    using System.Data.Entity.Migrations;

    public partial class InsertLookUpDataInDb : DbMigration
    {
        public override void Up()
        {
            Sql(@"SET IDENTITY_INSERT [dbo].[Controls] ON
INSERT INTO [dbo].[Controls] ([ControlId], [Name]) VALUES (1, N'Da')
INSERT INTO [dbo].[Controls] ([ControlId], [Name]) VALUES (2, N'Ne')
SET IDENTITY_INSERT [dbo].[Controls] OFF");
            Sql(@"SET IDENTITY_INSERT [dbo].[Status] ON
INSERT INTO [dbo].[Status] ([StatusId], [Name]) VALUES (1, N'Potpuno implementiran')
INSERT INTO [dbo].[Status] ([StatusId], [Name]) VALUES (2, N'Djelomice implementiran')
INSERT INTO [dbo].[Status] ([StatusId], [Name]) VALUES (3, N'Nije implementiran')
SET IDENTITY_INSERT [dbo].[Status] OFF
");
            Sql(@"SET IDENTITY_INSERT [dbo].[Roles] ON
INSERT INTO [dbo].[Roles] ([RoleId], [RoleName]) VALUES (1, N'admin')
INSERT INTO [dbo].[Roles] ([RoleId], [RoleName]) VALUES (2, N'user')
INSERT INTO [dbo].[Roles] ([RoleId], [RoleName]) VALUES (3, N'guest')
INSERT INTO [dbo].[Roles] ([RoleId], [RoleName]) VALUES (4, N'dev')
SET IDENTITY_INSERT [dbo].[Roles] OFF
");
            Sql(@"SET IDENTITY_INSERT [dbo].[Reasons] ON
INSERT INTO [dbo].[Reasons] ([ReasonId], [Name]) VALUES (1, N'Zakonska obaveza')
INSERT INTO [dbo].[Reasons] ([ReasonId], [Name]) VALUES (2, N'Ugovorna obaveza')
INSERT INTO [dbo].[Reasons] ([ReasonId], [Name]) VALUES (3, N'Poslovna potreba')
INSERT INTO [dbo].[Reasons] ([ReasonId], [Name]) VALUES (4, N'Procjena rizika')
INSERT INTO [dbo].[Reasons] ([ReasonId], [Name]) VALUES (5, N'Dobra praksa')
INSERT INTO [dbo].[Reasons] ([ReasonId], [Name]) VALUES (6, N'Drugi razlog')
INSERT INTO [dbo].[Reasons] ([ReasonId], [Name]) VALUES (7, N'Nije primjenjivo')
SET IDENTITY_INSERT [dbo].[Reasons] OFF
");
            Sql(@"SET IDENTITY_INSERT [dbo].[Norms] ON
INSERT INTO [dbo].[Norms] ([NormId], [Name], [Description]) VALUES (1, N'HRN ISO/IEC 27001:2013', N'Informacijska tehnologija - Sigurnosne tehnike - Sustavi upravljanja informacijskom sigurnoš?u - Zahtjevi')
INSERT INTO [dbo].[Norms] ([NormId], [Name], [Description]) VALUES (2, N'HRN ISO/IEC 27002:2013', N'Information technology – Security techniques – Code of practice for information security controls')
SET IDENTITY_INSERT [dbo].[Norms] OFF");
            Sql(@"SET IDENTITY_INSERT [dbo].[NormItems] ON
INSERT INTO [dbo].[NormItems] ([NormItemId], [Name], [IsItem], [Order], [ParentId], [NormId]) VALUES (1, N'Kontekst organizacije', 0, 4, NULL, 1)
INSERT INTO [dbo].[NormItems] ([NormItemId], [Name], [IsItem], [Order], [ParentId], [NormId]) VALUES (2, N'Razumijevanje organizacije i njenog konteksta', 1, 1, 1, 1)
INSERT INTO [dbo].[NormItems] ([NormItemId], [Name], [IsItem], [Order], [ParentId], [NormId]) VALUES (3, N'Razumijevanje potreba i o?ekivanja zainteresiranih strana', 1, 2, 1, 1)
INSERT INTO [dbo].[NormItems] ([NormItemId], [Name], [IsItem], [Order], [ParentId], [NormId]) VALUES (4, N'Definiranje opsega ISMS-a', 1, 3, 1, 1)
INSERT INTO [dbo].[NormItems] ([NormItemId], [Name], [IsItem], [Order], [ParentId], [NormId]) VALUES (5, N'Sustav upravljanja informacijskom sigurnoš?u', 1, 4, 1, 1)
INSERT INTO [dbo].[NormItems] ([NormItemId], [Name], [IsItem], [Order], [ParentId], [NormId]) VALUES (6, N'Rukovodstvo', 0, 5, NULL, 1)
INSERT INTO [dbo].[NormItems] ([NormItemId], [Name], [IsItem], [Order], [ParentId], [NormId]) VALUES (7, N'Rukovodstvo i predanost menadžmenta', 1, 1, 6, 1)
INSERT INTO [dbo].[NormItems] ([NormItemId], [Name], [IsItem], [Order], [ParentId], [NormId]) VALUES (8, N'ISMS politika', 1, 2, 6, 1)
INSERT INTO [dbo].[NormItems] ([NormItemId], [Name], [IsItem], [Order], [ParentId], [NormId]) VALUES (9, N'Uloge, odgovornosti i ovlasti', 1, 3, 6, 1)
INSERT INTO [dbo].[NormItems] ([NormItemId], [Name], [IsItem], [Order], [ParentId], [NormId]) VALUES (10, N'Planiranje', 0, 6, NULL, 1)
INSERT INTO [dbo].[NormItems] ([NormItemId], [Name], [IsItem], [Order], [ParentId], [NormId]) VALUES (11, N'Aktivnosti za prepoznavanje rizika i prilika', 0, 1, 10, 1)
INSERT INTO [dbo].[NormItems] ([NormItemId], [Name], [IsItem], [Order], [ParentId], [NormId]) VALUES (12, N'Op?enito', 1, 1, 11, 1)
INSERT INTO [dbo].[NormItems] ([NormItemId], [Name], [IsItem], [Order], [ParentId], [NormId]) VALUES (13, N'Procjena rizika informacijske sigurnosti', 1, 2, 11, 1)
INSERT INTO [dbo].[NormItems] ([NormItemId], [Name], [IsItem], [Order], [ParentId], [NormId]) VALUES (14, N'Obrada rizika informacijske sigurnosti', 1, 3, 11, 1)
INSERT INTO [dbo].[NormItems] ([NormItemId], [Name], [IsItem], [Order], [ParentId], [NormId]) VALUES (15, N'Ciljevi ISMS-a i planovi za njihovo ostvarivanje', 1, 2, 10, 1)
INSERT INTO [dbo].[NormItems] ([NormItemId], [Name], [IsItem], [Order], [ParentId], [NormId]) VALUES (16, N'Podrška', 0, 7, NULL, 1)
INSERT INTO [dbo].[NormItems] ([NormItemId], [Name], [IsItem], [Order], [ParentId], [NormId]) VALUES (17, N'Resursi', 1, 1, 16, 1)
INSERT INTO [dbo].[NormItems] ([NormItemId], [Name], [IsItem], [Order], [ParentId], [NormId]) VALUES (18, N'Kompetencije', 1, 2, 16, 1)
INSERT INTO [dbo].[NormItems] ([NormItemId], [Name], [IsItem], [Order], [ParentId], [NormId]) VALUES (19, N'Awareness', 1, 3, 16, 1)
INSERT INTO [dbo].[NormItems] ([NormItemId], [Name], [IsItem], [Order], [ParentId], [NormId]) VALUES (20, N'Komunikacija', 1, 4, 16, 1)
INSERT INTO [dbo].[NormItems] ([NormItemId], [Name], [IsItem], [Order], [ParentId], [NormId]) VALUES (21, N'Dokumentirane informacije', 0, 5, 16, 1)
INSERT INTO [dbo].[NormItems] ([NormItemId], [Name], [IsItem], [Order], [ParentId], [NormId]) VALUES (22, N'Op?enito', 1, 1, 21, 1)
INSERT INTO [dbo].[NormItems] ([NormItemId], [Name], [IsItem], [Order], [ParentId], [NormId]) VALUES (23, N'Izrada i ažuriranje', 1, 2, 21, 1)
INSERT INTO [dbo].[NormItems] ([NormItemId], [Name], [IsItem], [Order], [ParentId], [NormId]) VALUES (24, N'Kontrola dokumentiranih informacija', 1, 3, 21, 1)
INSERT INTO [dbo].[NormItems] ([NormItemId], [Name], [IsItem], [Order], [ParentId], [NormId]) VALUES (25, N'Operacije', 0, 8, NULL, 1)
INSERT INTO [dbo].[NormItems] ([NormItemId], [Name], [IsItem], [Order], [ParentId], [NormId]) VALUES (26, N'Operativno planiranje i nadzor', 1, 1, 25, 1)
INSERT INTO [dbo].[NormItems] ([NormItemId], [Name], [IsItem], [Order], [ParentId], [NormId]) VALUES (27, N'Procjena rizika informacijske sigurnosti', 1, 2, 25, 1)
INSERT INTO [dbo].[NormItems] ([NormItemId], [Name], [IsItem], [Order], [ParentId], [NormId]) VALUES (28, N'Obrada rizika informacijske sigurnosti', 1, 3, 25, 1)
INSERT INTO [dbo].[NormItems] ([NormItemId], [Name], [IsItem], [Order], [ParentId], [NormId]) VALUES (29, N'Ocjenjivanje uspješnosti', 0, 9, NULL, 1)
INSERT INTO [dbo].[NormItems] ([NormItemId], [Name], [IsItem], [Order], [ParentId], [NormId]) VALUES (30, N'Pra?enje, mjerenje, analiza i procjena', 1, 1, 29, 1)
INSERT INTO [dbo].[NormItems] ([NormItemId], [Name], [IsItem], [Order], [ParentId], [NormId]) VALUES (31, N'Interni audit', 1, 2, 29, 1)
INSERT INTO [dbo].[NormItems] ([NormItemId], [Name], [IsItem], [Order], [ParentId], [NormId]) VALUES (32, N'Ocjena sustava od strane Uprave', 1, 3, 29, 1)
INSERT INTO [dbo].[NormItems] ([NormItemId], [Name], [IsItem], [Order], [ParentId], [NormId]) VALUES (33, N'Poboljšanja', 0, 10, NULL, 1)
INSERT INTO [dbo].[NormItems] ([NormItemId], [Name], [IsItem], [Order], [ParentId], [NormId]) VALUES (34, N'Nesukladnosti i korektivne aktivnosti', 1, 1, 33, 1)
INSERT INTO [dbo].[NormItems] ([NormItemId], [Name], [IsItem], [Order], [ParentId], [NormId]) VALUES (35, N'Kontinuirano poboljšavanje', 1, 2, 33, 1)
INSERT INTO [dbo].[NormItems] ([NormItemId], [Name], [IsItem], [Order], [ParentId], [NormId]) VALUES (36, N'Politike ISMS-a', 0, 5, NULL, 2)
INSERT INTO [dbo].[NormItems] ([NormItemId], [Name], [IsItem], [Order], [ParentId], [NormId]) VALUES (37, N'Politika informacijske sigurnosti', 0, 1, 36, 2)
INSERT INTO [dbo].[NormItems] ([NormItemId], [Name], [IsItem], [Order], [ParentId], [NormId]) VALUES (38, N'Politike informacijske sigurnosti', 1, 1, 37, 2)
INSERT INTO [dbo].[NormItems] ([NormItemId], [Name], [IsItem], [Order], [ParentId], [NormId]) VALUES (39, N'Provjera politike informacijske sigurnosti', 1, 2, 37, 2)
INSERT INTO [dbo].[NormItems] ([NormItemId], [Name], [IsItem], [Order], [ParentId], [NormId]) VALUES (40, N'Organizacija informacijske sigurnosti', 0, 6, NULL, 2)
INSERT INTO [dbo].[NormItems] ([NormItemId], [Name], [IsItem], [Order], [ParentId], [NormId]) VALUES (41, N'Unutarnja organizacija', 0, 1, 40, 2)
INSERT INTO [dbo].[NormItems] ([NormItemId], [Name], [IsItem], [Order], [ParentId], [NormId]) VALUES (42, N'Uloge i odgovornosti u informacijskoj sigurnostia', 1, 1, 41, 2)
INSERT INTO [dbo].[NormItems] ([NormItemId], [Name], [IsItem], [Order], [ParentId], [NormId]) VALUES (43, N'Odjeljivanje funkcija', 1, 2, 41, 2)
INSERT INTO [dbo].[NormItems] ([NormItemId], [Name], [IsItem], [Order], [ParentId], [NormId]) VALUES (44, N'Kontakt s nadležnim tijelima', 1, 3, 41, 2)
INSERT INTO [dbo].[NormItems] ([NormItemId], [Name], [IsItem], [Order], [ParentId], [NormId]) VALUES (45, N'Kontakti s posebnim interesnim grupama', 1, 4, 41, 2)
INSERT INTO [dbo].[NormItems] ([NormItemId], [Name], [IsItem], [Order], [ParentId], [NormId]) VALUES (46, N'Informacijska sigurnost u upravljanju projektima', 1, 5, 41, 2)
INSERT INTO [dbo].[NormItems] ([NormItemId], [Name], [IsItem], [Order], [ParentId], [NormId]) VALUES (47, N'Mobilni ure?aji i rad na daljinu', 0, 2, 40, 2)
INSERT INTO [dbo].[NormItems] ([NormItemId], [Name], [IsItem], [Order], [ParentId], [NormId]) VALUES (48, N'Mobilni ure?aji', 1, 1, 47, 2)
INSERT INTO [dbo].[NormItems] ([NormItemId], [Name], [IsItem], [Order], [ParentId], [NormId]) VALUES (49, N'Rad na daljinu', 1, 2, 47, 2)
INSERT INTO [dbo].[NormItems] ([NormItemId], [Name], [IsItem], [Order], [ParentId], [NormId]) VALUES (50, N'Sigurnost ljudskih resursa', 0, 7, NULL, 2)
INSERT INTO [dbo].[NormItems] ([NormItemId], [Name], [IsItem], [Order], [ParentId], [NormId]) VALUES (51, N'Prije zaposlenja', 0, 1, 50, 2)
INSERT INTO [dbo].[NormItems] ([NormItemId], [Name], [IsItem], [Order], [ParentId], [NormId]) VALUES (52, N'Provjeravanje', 1, 1, 51, 2)
INSERT INTO [dbo].[NormItems] ([NormItemId], [Name], [IsItem], [Order], [ParentId], [NormId]) VALUES (53, N'Trajanje i uvjeti zaposlenja', 1, 2, 51, 2)
INSERT INTO [dbo].[NormItems] ([NormItemId], [Name], [IsItem], [Order], [ParentId], [NormId]) VALUES (54, N'Sigurnost ljudskih resursa', 0, 2, 50, 2)
INSERT INTO [dbo].[NormItems] ([NormItemId], [Name], [IsItem], [Order], [ParentId], [NormId]) VALUES (55, N'Odgovornost uprave', 1, 1, 54, 2)
INSERT INTO [dbo].[NormItems] ([NormItemId], [Name], [IsItem], [Order], [ParentId], [NormId]) VALUES (56, N'Razina svijesti o informacijskoj sigurnosti, obrazovanje i obu?avanje', 1, 2, 54, 2)
INSERT INTO [dbo].[NormItems] ([NormItemId], [Name], [IsItem], [Order], [ParentId], [NormId]) VALUES (57, N'Disciplinski postupak', 1, 3, 54, 2)
INSERT INTO [dbo].[NormItems] ([NormItemId], [Name], [IsItem], [Order], [ParentId], [NormId]) VALUES (58, N'Prekid ili promjena zaposlenja', 0, 3, 50, 2)
INSERT INTO [dbo].[NormItems] ([NormItemId], [Name], [IsItem], [Order], [ParentId], [NormId]) VALUES (59, N'Odgovornost za prekid ili promjenu zaposlenja', 1, 1, 58, 2)
INSERT INTO [dbo].[NormItems] ([NormItemId], [Name], [IsItem], [Order], [ParentId], [NormId]) VALUES (60, N'Upravljanje imovinom', 0, 8, NULL, 2)
INSERT INTO [dbo].[NormItems] ([NormItemId], [Name], [IsItem], [Order], [ParentId], [NormId]) VALUES (61, N'Upravljanje imovinom', 0, 1, 60, 2)
INSERT INTO [dbo].[NormItems] ([NormItemId], [Name], [IsItem], [Order], [ParentId], [NormId]) VALUES (62, N'Popis imovine', 1, 1, 61, 2)
INSERT INTO [dbo].[NormItems] ([NormItemId], [Name], [IsItem], [Order], [ParentId], [NormId]) VALUES (63, N'Vlasništvo nad imovinom', 1, 2, 61, 2)
INSERT INTO [dbo].[NormItems] ([NormItemId], [Name], [IsItem], [Order], [ParentId], [NormId]) VALUES (64, N'Prihvatljivo korištenje imovinom', 1, 3, 61, 2)
INSERT INTO [dbo].[NormItems] ([NormItemId], [Name], [IsItem], [Order], [ParentId], [NormId]) VALUES (65, N'Povrat imovine', 1, 4, 61, 2)
INSERT INTO [dbo].[NormItems] ([NormItemId], [Name], [IsItem], [Order], [ParentId], [NormId]) VALUES (66, N'Klasifikacija informacija', 0, 2, 60, 2)
INSERT INTO [dbo].[NormItems] ([NormItemId], [Name], [IsItem], [Order], [ParentId], [NormId]) VALUES (67, N'Klasifikacija informacija', 1, 1, 66, 2)
INSERT INTO [dbo].[NormItems] ([NormItemId], [Name], [IsItem], [Order], [ParentId], [NormId]) VALUES (68, N'Ozna?avanje informacija', 1, 2, 66, 2)
INSERT INTO [dbo].[NormItems] ([NormItemId], [Name], [IsItem], [Order], [ParentId], [NormId]) VALUES (69, N'Rukovanje imovinom', 1, 3, 66, 2)
INSERT INTO [dbo].[NormItems] ([NormItemId], [Name], [IsItem], [Order], [ParentId], [NormId]) VALUES (70, N'Rukovanje medijima', 0, 3, 60, 2)
INSERT INTO [dbo].[NormItems] ([NormItemId], [Name], [IsItem], [Order], [ParentId], [NormId]) VALUES (71, N'Upravljanje uklonjivim medijima', 1, 1, 70, 2)
INSERT INTO [dbo].[NormItems] ([NormItemId], [Name], [IsItem], [Order], [ParentId], [NormId]) VALUES (72, N'Odbacivanje medija', 1, 2, 70, 2)
INSERT INTO [dbo].[NormItems] ([NormItemId], [Name], [IsItem], [Order], [ParentId], [NormId]) VALUES (73, N'Prijevoz fizi?kih medija', 1, 3, 70, 2)
INSERT INTO [dbo].[NormItems] ([NormItemId], [Name], [IsItem], [Order], [ParentId], [NormId]) VALUES (74, N'Kontrola pristupa', 0, 9, NULL, 2)
INSERT INTO [dbo].[NormItems] ([NormItemId], [Name], [IsItem], [Order], [ParentId], [NormId]) VALUES (75, N'Poslovni zahtjevi kontrole pristupa', 0, 1, 74, 2)
INSERT INTO [dbo].[NormItems] ([NormItemId], [Name], [IsItem], [Order], [ParentId], [NormId]) VALUES (76, N'Granice fizi?kog sigurnosnog prostora', 1, 1, 75, 2)
INSERT INTO [dbo].[NormItems] ([NormItemId], [Name], [IsItem], [Order], [ParentId], [NormId]) VALUES (77, N'Kontrole fizi?kog pristupa', 1, 2, 75, 2)
INSERT INTO [dbo].[NormItems] ([NormItemId], [Name], [IsItem], [Order], [ParentId], [NormId]) VALUES (78, N'Upravljanje korisni?kim pristupom', 0, 2, 74, 2)
INSERT INTO [dbo].[NormItems] ([NormItemId], [Name], [IsItem], [Order], [ParentId], [NormId]) VALUES (79, N'Prijava i odjava korisnika', 1, 1, 78, 2)
INSERT INTO [dbo].[NormItems] ([NormItemId], [Name], [IsItem], [Order], [ParentId], [NormId]) VALUES (80, N'Dodjeljivanje korisni?kih prava', 1, 2, 78, 2)
INSERT INTO [dbo].[NormItems] ([NormItemId], [Name], [IsItem], [Order], [ParentId], [NormId]) VALUES (81, N'Upravljanje povlaštenim pravima pristupa', 1, 3, 78, 2)
INSERT INTO [dbo].[NormItems] ([NormItemId], [Name], [IsItem], [Order], [ParentId], [NormId]) VALUES (82, N'Upravljanje tajnim informacijama za autentifikaciju korisnika', 1, 4, 78, 2)
INSERT INTO [dbo].[NormItems] ([NormItemId], [Name], [IsItem], [Order], [ParentId], [NormId]) VALUES (83, N'Provjera prava korisni?kog pristupa', 1, 5, 78, 2)
INSERT INTO [dbo].[NormItems] ([NormItemId], [Name], [IsItem], [Order], [ParentId], [NormId]) VALUES (84, N'Ukidanje ili podešavanje prava pristupa', 1, 6, 78, 2)
INSERT INTO [dbo].[NormItems] ([NormItemId], [Name], [IsItem], [Order], [ParentId], [NormId]) VALUES (85, N'Odgovornosti korisnika', 0, 3, 74, 2)
INSERT INTO [dbo].[NormItems] ([NormItemId], [Name], [IsItem], [Order], [ParentId], [NormId]) VALUES (86, N'Korištenje tajnih informacija za autentifikaciju', 1, 1, 85, 2)
INSERT INTO [dbo].[NormItems] ([NormItemId], [Name], [IsItem], [Order], [ParentId], [NormId]) VALUES (87, N'Kontrola pristupa aplikacijama i sustavu', 0, 4, 74, 2)
INSERT INTO [dbo].[NormItems] ([NormItemId], [Name], [IsItem], [Order], [ParentId], [NormId]) VALUES (88, N'Ograni?avanje pristupa informacijama', 1, 1, 87, 2)
INSERT INTO [dbo].[NormItems] ([NormItemId], [Name], [IsItem], [Order], [ParentId], [NormId]) VALUES (89, N'Procedura sigurnog prijavljivanja', 1, 2, 87, 2)
INSERT INTO [dbo].[NormItems] ([NormItemId], [Name], [IsItem], [Order], [ParentId], [NormId]) VALUES (90, N'Upravljanje korisni?kim zaporkama', 1, 3, 87, 2)
INSERT INTO [dbo].[NormItems] ([NormItemId], [Name], [IsItem], [Order], [ParentId], [NormId]) VALUES (91, N'Uporaba privilegiranih utility programa', 1, 4, 87, 2)
INSERT INTO [dbo].[NormItems] ([NormItemId], [Name], [IsItem], [Order], [ParentId], [NormId]) VALUES (92, N'Kontrola pristupa izvornom kodu programa', 1, 5, 87, 2)
INSERT INTO [dbo].[NormItems] ([NormItemId], [Name], [IsItem], [Order], [ParentId], [NormId]) VALUES (93, N'Kriptografija', 0, 10, NULL, 2)
INSERT INTO [dbo].[NormItems] ([NormItemId], [Name], [IsItem], [Order], [ParentId], [NormId]) VALUES (94, N'Kriptografske kontrole', 0, 1, 93, 2)
INSERT INTO [dbo].[NormItems] ([NormItemId], [Name], [IsItem], [Order], [ParentId], [NormId]) VALUES (95, N'Politika korištenja kriptografskih kontrola', 1, 1, 94, 2)
INSERT INTO [dbo].[NormItems] ([NormItemId], [Name], [IsItem], [Order], [ParentId], [NormId]) VALUES (96, N'Upravljanje klju?evima', 1, 2, 94, 2)
INSERT INTO [dbo].[NormItems] ([NormItemId], [Name], [IsItem], [Order], [ParentId], [NormId]) VALUES (97, N'Fizi?ka sigurnost i sigurnost okruženja', 0, 11, NULL, 2)
INSERT INTO [dbo].[NormItems] ([NormItemId], [Name], [IsItem], [Order], [ParentId], [NormId]) VALUES (98, N'Granice fizi?ke sigurnosti', 0, 1, 97, 2)
INSERT INTO [dbo].[NormItems] ([NormItemId], [Name], [IsItem], [Order], [ParentId], [NormId]) VALUES (99, N'Politika kontrole pristupa', 1, 1, 98, 2)
INSERT INTO [dbo].[NormItems] ([NormItemId], [Name], [IsItem], [Order], [ParentId], [NormId]) VALUES (100, N'Kontrole fizi?kog pristupa', 1, 2, 98, 2)
INSERT INTO [dbo].[NormItems] ([NormItemId], [Name], [IsItem], [Order], [ParentId], [NormId]) VALUES (101, N'Osiguranje ureda, prostorija i opreme', 1, 3, 98, 2)
INSERT INTO [dbo].[NormItems] ([NormItemId], [Name], [IsItem], [Order], [ParentId], [NormId]) VALUES (102, N'Zaštita od vanjskih prijetnji i nepogoda', 1, 4, 98, 2)
INSERT INTO [dbo].[NormItems] ([NormItemId], [Name], [IsItem], [Order], [ParentId], [NormId]) VALUES (103, N'Rad u osiguranim podru?jima', 1, 5, 98, 2)
INSERT INTO [dbo].[NormItems] ([NormItemId], [Name], [IsItem], [Order], [ParentId], [NormId]) VALUES (104, N'Podru?ja sa javnim pristupom, podru?ja za istovar i utovar', 1, 6, 98, 2)
INSERT INTO [dbo].[NormItems] ([NormItemId], [Name], [IsItem], [Order], [ParentId], [NormId]) VALUES (105, N'Oprema', 0, 2, 97, 2)
INSERT INTO [dbo].[NormItems] ([NormItemId], [Name], [IsItem], [Order], [ParentId], [NormId]) VALUES (106, N'Zaštita opreme', 1, 1, 105, 2)
INSERT INTO [dbo].[NormItems] ([NormItemId], [Name], [IsItem], [Order], [ParentId], [NormId]) VALUES (107, N'Potporne usluge', 1, 2, 105, 2)
INSERT INTO [dbo].[NormItems] ([NormItemId], [Name], [IsItem], [Order], [ParentId], [NormId]) VALUES (108, N'Sigurnost oži?enja', 1, 3, 105, 2)
INSERT INTO [dbo].[NormItems] ([NormItemId], [Name], [IsItem], [Order], [ParentId], [NormId]) VALUES (109, N'Održavanje opreme', 1, 4, 105, 2)
INSERT INTO [dbo].[NormItems] ([NormItemId], [Name], [IsItem], [Order], [ParentId], [NormId]) VALUES (110, N'Iznošenje imovine', 1, 5, 105, 2)
INSERT INTO [dbo].[NormItems] ([NormItemId], [Name], [IsItem], [Order], [ParentId], [NormId]) VALUES (111, N'Sigurnost opreme izvan prostora', 1, 6, 105, 2)
INSERT INTO [dbo].[NormItems] ([NormItemId], [Name], [IsItem], [Order], [ParentId], [NormId]) VALUES (112, N'Sigurno odbacivanje ili ponovno korištenje opreme', 1, 7, 105, 2)
INSERT INTO [dbo].[NormItems] ([NormItemId], [Name], [IsItem], [Order], [ParentId], [NormId]) VALUES (113, N'Korisni?ka oprema bez nadzora', 1, 8, 105, 2)
INSERT INTO [dbo].[NormItems] ([NormItemId], [Name], [IsItem], [Order], [ParentId], [NormId]) VALUES (114, N'Politika praznog stola i zaslona', 1, 9, 105, 2)
INSERT INTO [dbo].[NormItems] ([NormItemId], [Name], [IsItem], [Order], [ParentId], [NormId]) VALUES (115, N'Operacijska sigurnost', 0, 12, NULL, 2)
INSERT INTO [dbo].[NormItems] ([NormItemId], [Name], [IsItem], [Order], [ParentId], [NormId]) VALUES (116, N'Radne procedure i odgovornosti', 0, 1, 115, 2)
INSERT INTO [dbo].[NormItems] ([NormItemId], [Name], [IsItem], [Order], [ParentId], [NormId]) VALUES (117, N'Dokumentirane radne procedure', 1, 1, 116, 2)
INSERT INTO [dbo].[NormItems] ([NormItemId], [Name], [IsItem], [Order], [ParentId], [NormId]) VALUES (118, N'Upravljanje promjenama', 1, 2, 116, 2)
INSERT INTO [dbo].[NormItems] ([NormItemId], [Name], [IsItem], [Order], [ParentId], [NormId]) VALUES (119, N'Upravljanje kapacitetom', 1, 3, 116, 2)
INSERT INTO [dbo].[NormItems] ([NormItemId], [Name], [IsItem], [Order], [ParentId], [NormId]) VALUES (120, N'Odvajanje razvojne, testne i produkcijske okoline', 1, 4, 116, 2)
INSERT INTO [dbo].[NormItems] ([NormItemId], [Name], [IsItem], [Order], [ParentId], [NormId]) VALUES (121, N'Zaštita od zlo?udnog koda', 0, 2, 115, 2)
INSERT INTO [dbo].[NormItems] ([NormItemId], [Name], [IsItem], [Order], [ParentId], [NormId]) VALUES (122, N'Kontrole za zaštitu od zlo?udnog koda', 1, 1, 121, 2)
INSERT INTO [dbo].[NormItems] ([NormItemId], [Name], [IsItem], [Order], [ParentId], [NormId]) VALUES (123, N'Sigurnosne kopije (backup)', 0, 3, 115, 2)
INSERT INTO [dbo].[NormItems] ([NormItemId], [Name], [IsItem], [Order], [ParentId], [NormId]) VALUES (124, N'Sigurnosne kopije informacija', 1, 1, 123, 2)
INSERT INTO [dbo].[NormItems] ([NormItemId], [Name], [IsItem], [Order], [ParentId], [NormId]) VALUES (125, N'Sigurnost sistemskih datoteka', 0, 4, 115, 2)
INSERT INTO [dbo].[NormItems] ([NormItemId], [Name], [IsItem], [Order], [ParentId], [NormId]) VALUES (126, N'Zapisi o doga?ajima', 1, 1, 125, 2)
INSERT INTO [dbo].[NormItems] ([NormItemId], [Name], [IsItem], [Order], [ParentId], [NormId]) VALUES (127, N'Zaštita logova', 1, 2, 125, 2)
INSERT INTO [dbo].[NormItems] ([NormItemId], [Name], [IsItem], [Order], [ParentId], [NormId]) VALUES (128, N'Zapisi administratora i operatera', 1, 3, 125, 2)
INSERT INTO [dbo].[NormItems] ([NormItemId], [Name], [IsItem], [Order], [ParentId], [NormId]) VALUES (129, N'Sinkronizacija satova', 1, 4, 125, 2)
INSERT INTO [dbo].[NormItems] ([NormItemId], [Name], [IsItem], [Order], [ParentId], [NormId]) VALUES (130, N'Kontrola produkcijskog softvera', 0, 5, 115, 2)
INSERT INTO [dbo].[NormItems] ([NormItemId], [Name], [IsItem], [Order], [ParentId], [NormId]) VALUES (131, N'Instalacija softvera na produkcijskom sustavu', 1, 1, 130, 2)
INSERT INTO [dbo].[NormItems] ([NormItemId], [Name], [IsItem], [Order], [ParentId], [NormId]) VALUES (132, N'Upravljanje tehni?kom ranjivoš?u', 0, 6, 115, 2)
INSERT INTO [dbo].[NormItems] ([NormItemId], [Name], [IsItem], [Order], [ParentId], [NormId]) VALUES (133, N'Upravljanje tehni?kom ranjivoš?u', 1, 1, 132, 2)
INSERT INTO [dbo].[NormItems] ([NormItemId], [Name], [IsItem], [Order], [ParentId], [NormId]) VALUES (134, N'Ograni?enja za instalaciju softvera', 1, 2, 132, 2)
INSERT INTO [dbo].[NormItems] ([NormItemId], [Name], [IsItem], [Order], [ParentId], [NormId]) VALUES (135, N'Razmatranje revizije informacijskih sustava', 0, 7, 115, 2)
INSERT INTO [dbo].[NormItems] ([NormItemId], [Name], [IsItem], [Order], [ParentId], [NormId]) VALUES (136, N'Kontrola revizije informacijskih sustava', 1, 1, 135, 2)
INSERT INTO [dbo].[NormItems] ([NormItemId], [Name], [IsItem], [Order], [ParentId], [NormId]) VALUES (137, N'Sigurnost komunikacija', 0, 13, NULL, 2)
INSERT INTO [dbo].[NormItems] ([NormItemId], [Name], [IsItem], [Order], [ParentId], [NormId]) VALUES (138, N'Upravljanje sigurnoš?u mreže', 0, 1, 137, 2)
INSERT INTO [dbo].[NormItems] ([NormItemId], [Name], [IsItem], [Order], [ParentId], [NormId]) VALUES (139, N'Kontrola mreže', 1, 1, 138, 2)
INSERT INTO [dbo].[NormItems] ([NormItemId], [Name], [IsItem], [Order], [ParentId], [NormId]) VALUES (140, N'Sigurnost mrežnih usluga', 1, 2, 138, 2)
INSERT INTO [dbo].[NormItems] ([NormItemId], [Name], [IsItem], [Order], [ParentId], [NormId]) VALUES (141, N'Odvajanje u mrežama', 1, 3, 138, 2)
INSERT INTO [dbo].[NormItems] ([NormItemId], [Name], [IsItem], [Order], [ParentId], [NormId]) VALUES (142, N'Razmjena informacija', 0, 2, 137, 2)
INSERT INTO [dbo].[NormItems] ([NormItemId], [Name], [IsItem], [Order], [ParentId], [NormId]) VALUES (143, N'Politike i procedure za razmjenu informacija', 1, 1, 142, 2)
INSERT INTO [dbo].[NormItems] ([NormItemId], [Name], [IsItem], [Order], [ParentId], [NormId]) VALUES (144, N'Sporazumi o razmjeni informacija', 1, 2, 142, 2)
INSERT INTO [dbo].[NormItems] ([NormItemId], [Name], [IsItem], [Order], [ParentId], [NormId]) VALUES (145, N'Elektronska razmjena informacija', 1, 3, 142, 2)
INSERT INTO [dbo].[NormItems] ([NormItemId], [Name], [IsItem], [Order], [ParentId], [NormId]) VALUES (146, N'Sporazumi o povjerljivosti', 1, 4, 142, 2)
INSERT INTO [dbo].[NormItems] ([NormItemId], [Name], [IsItem], [Order], [ParentId], [NormId]) VALUES (147, N'Nabava, razvoj i održavanje sustava', 0, 14, NULL, 2)
INSERT INTO [dbo].[NormItems] ([NormItemId], [Name], [IsItem], [Order], [ParentId], [NormId]) VALUES (148, N'Sigurnosni zahtjevi za informacijske sustave', 0, 1, 147, 2)
INSERT INTO [dbo].[NormItems] ([NormItemId], [Name], [IsItem], [Order], [ParentId], [NormId]) VALUES (149, N'Analiza i specifikacija sigurnosnih zahtjeva', 1, 1, 148, 2)
INSERT INTO [dbo].[NormItems] ([NormItemId], [Name], [IsItem], [Order], [ParentId], [NormId]) VALUES (150, N'Sigurnost aplikacija na javnim mrežama', 1, 2, 148, 2)
INSERT INTO [dbo].[NormItems] ([NormItemId], [Name], [IsItem], [Order], [ParentId], [NormId]) VALUES (151, N'Zaštita transakcija', 1, 3, 148, 2)
INSERT INTO [dbo].[NormItems] ([NormItemId], [Name], [IsItem], [Order], [ParentId], [NormId]) VALUES (152, N'Sigurnost u procesima razvoja i podrške', 0, 2, 147, 2)
INSERT INTO [dbo].[NormItems] ([NormItemId], [Name], [IsItem], [Order], [ParentId], [NormId]) VALUES (153, N'Sigurnosna politika razvoja', 1, 1, 152, 2)
INSERT INTO [dbo].[NormItems] ([NormItemId], [Name], [IsItem], [Order], [ParentId], [NormId]) VALUES (154, N'Procedure kontrole promjene sustava', 1, 2, 152, 2)
INSERT INTO [dbo].[NormItems] ([NormItemId], [Name], [IsItem], [Order], [ParentId], [NormId]) VALUES (155, N'Tehni?ka provjera aplikacija nakon promjena operativne platforme', 1, 3, 152, 2)
INSERT INTO [dbo].[NormItems] ([NormItemId], [Name], [IsItem], [Order], [ParentId], [NormId]) VALUES (156, N'Ograni?enje promjena softverskih paketa', 1, 4, 152, 2)
INSERT INTO [dbo].[NormItems] ([NormItemId], [Name], [IsItem], [Order], [ParentId], [NormId]) VALUES (157, N'Principi sigurnosti u inženjeringu IS-a', 1, 5, 152, 2)
INSERT INTO [dbo].[NormItems] ([NormItemId], [Name], [IsItem], [Order], [ParentId], [NormId]) VALUES (158, N'Sigurno razvojno okruženje', 1, 6, 152, 2)
INSERT INTO [dbo].[NormItems] ([NormItemId], [Name], [IsItem], [Order], [ParentId], [NormId]) VALUES (159, N'Razvoj povjeren vanjskim izvršiteljima', 1, 7, 152, 2)
INSERT INTO [dbo].[NormItems] ([NormItemId], [Name], [IsItem], [Order], [ParentId], [NormId]) VALUES (160, N'Sigurnosna testiranja sustava', 1, 8, 152, 2)
INSERT INTO [dbo].[NormItems] ([NormItemId], [Name], [IsItem], [Order], [ParentId], [NormId]) VALUES (161, N'Testiranje prihva?anja sustava', 1, 9, 152, 2)
INSERT INTO [dbo].[NormItems] ([NormItemId], [Name], [IsItem], [Order], [ParentId], [NormId]) VALUES (162, N'Testni podaci', 0, 3, 147, 2)
INSERT INTO [dbo].[NormItems] ([NormItemId], [Name], [IsItem], [Order], [ParentId], [NormId]) VALUES (163, N'Zaštita testnih podataka', 1, 1, 162, 2)
INSERT INTO [dbo].[NormItems] ([NormItemId], [Name], [IsItem], [Order], [ParentId], [NormId]) VALUES (164, N'Odnosi s dobavlja?ima', 0, 15, NULL, 2)
INSERT INTO [dbo].[NormItems] ([NormItemId], [Name], [IsItem], [Order], [ParentId], [NormId]) VALUES (165, N'Informacijska sigurnost u odnosu s dobavlja?ima', 0, 1, 164, 2)
INSERT INTO [dbo].[NormItems] ([NormItemId], [Name], [IsItem], [Order], [ParentId], [NormId]) VALUES (166, N'Politika sigurnosti za odnose s dobavlja?ima', 1, 1, 165, 2)
INSERT INTO [dbo].[NormItems] ([NormItemId], [Name], [IsItem], [Order], [ParentId], [NormId]) VALUES (167, N'Uklju?ivanje sigurnosti u ugovore s dobavlja?ima', 1, 2, 165, 2)
INSERT INTO [dbo].[NormItems] ([NormItemId], [Name], [IsItem], [Order], [ParentId], [NormId]) VALUES (168, N'Lanac nabave informacijsko-komunikacijske tehnologije', 1, 3, 165, 2)
INSERT INTO [dbo].[NormItems] ([NormItemId], [Name], [IsItem], [Order], [ParentId], [NormId]) VALUES (169, N'Upravljanje isporukama dobavlja?a', 0, 2, 165, 2)
INSERT INTO [dbo].[NormItems] ([NormItemId], [Name], [IsItem], [Order], [ParentId], [NormId]) VALUES (170, N'Nadzor i provjera usluga dobavlja?a', 1, 1, 168, 2)
INSERT INTO [dbo].[NormItems] ([NormItemId], [Name], [IsItem], [Order], [ParentId], [NormId]) VALUES (171, N'Upravljanje promjenama usluga dobavlja?a', 1, 2, 168, 2)
INSERT INTO [dbo].[NormItems] ([NormItemId], [Name], [IsItem], [Order], [ParentId], [NormId]) VALUES (172, N'Upravljanje s incidentima informacijske sigurnosti', 0, 16, NULL, 2)
INSERT INTO [dbo].[NormItems] ([NormItemId], [Name], [IsItem], [Order], [ParentId], [NormId]) VALUES (173, N'Upravljanje incidentima i unapre?enjima informacijske sigurnosti', 0, 1, 172, 2)
INSERT INTO [dbo].[NormItems] ([NormItemId], [Name], [IsItem], [Order], [ParentId], [NormId]) VALUES (174, N'Odgovornosti i procedure', 1, 1, 173, 2)
INSERT INTO [dbo].[NormItems] ([NormItemId], [Name], [IsItem], [Order], [ParentId], [NormId]) VALUES (175, N'Izvješ?ivanje o sigurnosnim doga?ajima', 1, 2, 173, 2)
INSERT INTO [dbo].[NormItems] ([NormItemId], [Name], [IsItem], [Order], [ParentId], [NormId]) VALUES (176, N'Izvješ?ivanje o sigurnosnim slabostima', 1, 3, 173, 2)
INSERT INTO [dbo].[NormItems] ([NormItemId], [Name], [IsItem], [Order], [ParentId], [NormId]) VALUES (177, N'Procjena i odlu?ivanje vezano za doga?aje informacijske sigurnosti', 1, 4, 173, 2)
INSERT INTO [dbo].[NormItems] ([NormItemId], [Name], [IsItem], [Order], [ParentId], [NormId]) VALUES (178, N'Odgovor na incidente informacijske sigurnosti', 1, 5, 173, 2)
INSERT INTO [dbo].[NormItems] ([NormItemId], [Name], [IsItem], [Order], [ParentId], [NormId]) VALUES (179, N'U?enje na sigurnosnim incidentima', 1, 6, 173, 2)
INSERT INTO [dbo].[NormItems] ([NormItemId], [Name], [IsItem], [Order], [ParentId], [NormId]) VALUES (180, N'Prikupljanje dokaza', 1, 7, 173, 2)
INSERT INTO [dbo].[NormItems] ([NormItemId], [Name], [IsItem], [Order], [ParentId], [NormId]) VALUES (181, N'Upravljanje kontinuitetom poslovanja s aspekta informacijske sigurnosti', 0, 17, NULL, 2)
INSERT INTO [dbo].[NormItems] ([NormItemId], [Name], [IsItem], [Order], [ParentId], [NormId]) VALUES (182, N'Prikupljanje dokaza', 0, 1, 181, 2)
INSERT INTO [dbo].[NormItems] ([NormItemId], [Name], [IsItem], [Order], [ParentId], [NormId]) VALUES (183, N'Planiranje kontinuiteta informacijske sigurnosti', 1, 1, 182, 2)
INSERT INTO [dbo].[NormItems] ([NormItemId], [Name], [IsItem], [Order], [ParentId], [NormId]) VALUES (184, N'Implementacija kontinuiteta informacijske sigurnosti', 1, 2, 182, 2)
INSERT INTO [dbo].[NormItems] ([NormItemId], [Name], [IsItem], [Order], [ParentId], [NormId]) VALUES (185, N'Verifikacija, provjera i evaluacija kontinuiteta informacijske sigurnosti', 1, 3, 182, 2)
INSERT INTO [dbo].[NormItems] ([NormItemId], [Name], [IsItem], [Order], [ParentId], [NormId]) VALUES (186, N'Redundantnost', 0, 2, 181, 2)
INSERT INTO [dbo].[NormItems] ([NormItemId], [Name], [IsItem], [Order], [ParentId], [NormId]) VALUES (187, N'Dostupnost opreme za obradu informacija', 1, 1, 186, 2)
INSERT INTO [dbo].[NormItems] ([NormItemId], [Name], [IsItem], [Order], [ParentId], [NormId]) VALUES (188, N'Sukladnost', 0, 18, NULL, 2)
INSERT INTO [dbo].[NormItems] ([NormItemId], [Name], [IsItem], [Order], [ParentId], [NormId]) VALUES (189, N'Redundantnost', 0, 1, 188, 2)
INSERT INTO [dbo].[NormItems] ([NormItemId], [Name], [IsItem], [Order], [ParentId], [NormId]) VALUES (190, N'Odre?ivanje primjenjivih zakona', 1, 1, 189, 2)
INSERT INTO [dbo].[NormItems] ([NormItemId], [Name], [IsItem], [Order], [ParentId], [NormId]) VALUES (191, N'Prava intelektualnog vlasništva', 1, 2, 189, 2)
INSERT INTO [dbo].[NormItems] ([NormItemId], [Name], [IsItem], [Order], [ParentId], [NormId]) VALUES (192, N'Zaštita zapisa', 1, 3, 189, 2)
INSERT INTO [dbo].[NormItems] ([NormItemId], [Name], [IsItem], [Order], [ParentId], [NormId]) VALUES (193, N'Zaštita podatakak i privatnost osobnih informacija', 1, 4, 189, 2)
INSERT INTO [dbo].[NormItems] ([NormItemId], [Name], [IsItem], [Order], [ParentId], [NormId]) VALUES (194, N'Odredbe o kriptografskim kontrolama', 1, 5, 189, 2)
INSERT INTO [dbo].[NormItems] ([NormItemId], [Name], [IsItem], [Order], [ParentId], [NormId]) VALUES (195, N'Provjera informacijske sigurnosti', 0, 2, 188, 2)
INSERT INTO [dbo].[NormItems] ([NormItemId], [Name], [IsItem], [Order], [ParentId], [NormId]) VALUES (196, N'Neovisna provjera informacijske sigurnosti', 1, 1, 195, 2)
INSERT INTO [dbo].[NormItems] ([NormItemId], [Name], [IsItem], [Order], [ParentId], [NormId]) VALUES (197, N'Uskla?enost sa sigurnosnim pravilima i standardima', 1, 2, 195, 2)
INSERT INTO [dbo].[NormItems] ([NormItemId], [Name], [IsItem], [Order], [ParentId], [NormId]) VALUES (198, N'Provjera tehni?ke sukladnosti', 1, 3, 195, 2)
SET IDENTITY_INSERT [dbo].[NormItems] OFF
");
            Sql(@"INSERT INTO [dbo].[ReportValueAdditionalItems] ([NormId], [HaveReason], [HaveControl]) VALUES (1, 0, 0)
INSERT INTO [dbo].[ReportValueAdditionalItems] ([NormId], [HaveReason], [HaveControl]) VALUES (2, 1, 1)
");
            Sql(@"SET IDENTITY_INSERT [dbo].[Organisations] ON
INSERT INTO [dbo].[Organisations] ([OrganisationId], [Name], [Address], [Ownership], [Type], [EmployeesNumber], [Size], [GuardService], [VideoSurveillance], [BuildingPossession], [ITService], [Location], [AssetOne], [AssetTwo], [AssetThree], [Created], [Modified], [IsActive]) VALUES (1, N'Test organizacija', N'Test address', N'Državno', N'Nacionalna', N'1-49', N'Srednja', N'Da', N'Da', N'Da', N'Da', N'Test lokacija', N'DA', N'asd', N'Test', N'2018-10-15 21:47:06', NULL, 1)
INSERT INTO [dbo].[Organisations] ([OrganisationId], [Name], [Address], [Ownership], [Type], [EmployeesNumber], [Size], [GuardService], [VideoSurveillance], [BuildingPossession], [ITService], [Location], [AssetOne], [AssetTwo], [AssetThree], [Created], [Modified], [IsActive]) VALUES (2, N'Druga test organizacija', N'Test address', N'Državno', N'Nacionalna', N'1-49', N'Srednja', N'Da', N'Da', N'Da', N'Da', N'Test lokacija', N'DA', N'asd', N'Test', N'2018-10-15 21:47:06', NULL, 1)
SET IDENTITY_INSERT [dbo].[Organisations] OFF");
            Sql(@"SET IDENTITY_INSERT [dbo].[Reports] ON
INSERT INTO [dbo].[Reports] ([ReportId], [Name], [NormId], [OrganisationId], [Created], [Modified], [IsActive]) VALUES (1, N'Custom report', 1, 1, N'2018-10-15 21:47:06', NULL, 0)
INSERT INTO [dbo].[Reports] ([ReportId], [Name], [NormId], [OrganisationId], [Created], [Modified], [IsActive]) VALUES (2, N'Custom report 2', 2, 2, N'2018-10-15 21:47:06', NULL, 0)
SET IDENTITY_INSERT [dbo].[Reports] OFF");
            Sql(@"INSERT INTO [dbo].[ReportValues] ([ReportId], [NormItemId], [Note], [StatusId], [ReportValue_ReportId], [ReportValue_NormItemId], [ControlId], [ReasonId]) VALUES (1, 1, NULL, NULL, NULL, NULL, NULL, NULL)
INSERT INTO [dbo].[ReportValues] ([ReportId], [NormItemId], [Note], [StatusId], [ReportValue_ReportId], [ReportValue_NormItemId], [ControlId], [ReasonId]) VALUES (1, 2, N'Napomena test', 1, 1, 1, NULL, NULL)
INSERT INTO [dbo].[ReportValues] ([ReportId], [NormItemId], [Note], [StatusId], [ReportValue_ReportId], [ReportValue_NormItemId], [ControlId], [ReasonId]) VALUES (1, 3, N'Napomena test', 1, 1, 1, NULL, NULL)
INSERT INTO [dbo].[ReportValues] ([ReportId], [NormItemId], [Note], [StatusId], [ReportValue_ReportId], [ReportValue_NormItemId], [ControlId], [ReasonId]) VALUES (1, 4, N'Napomena test', 1, 1, 1, NULL, NULL)
INSERT INTO [dbo].[ReportValues] ([ReportId], [NormItemId], [Note], [StatusId], [ReportValue_ReportId], [ReportValue_NormItemId], [ControlId], [ReasonId]) VALUES (1, 5, N'Napomena test', 1, 1, 1, NULL, NULL)
INSERT INTO [dbo].[ReportValues] ([ReportId], [NormItemId], [Note], [StatusId], [ReportValue_ReportId], [ReportValue_NormItemId], [ControlId], [ReasonId]) VALUES (1, 6, NULL, NULL, NULL, NULL, NULL, NULL)
INSERT INTO [dbo].[ReportValues] ([ReportId], [NormItemId], [Note], [StatusId], [ReportValue_ReportId], [ReportValue_NormItemId], [ControlId], [ReasonId]) VALUES (1, 7, N'Napomena test', 1, 1, 6, NULL, NULL)
INSERT INTO [dbo].[ReportValues] ([ReportId], [NormItemId], [Note], [StatusId], [ReportValue_ReportId], [ReportValue_NormItemId], [ControlId], [ReasonId]) VALUES (1, 8, N'Napomena test', 1, 1, 6, NULL, NULL)
INSERT INTO [dbo].[ReportValues] ([ReportId], [NormItemId], [Note], [StatusId], [ReportValue_ReportId], [ReportValue_NormItemId], [ControlId], [ReasonId]) VALUES (1, 9, N'Napomena test', 1, 1, 6, NULL, NULL)
INSERT INTO [dbo].[ReportValues] ([ReportId], [NormItemId], [Note], [StatusId], [ReportValue_ReportId], [ReportValue_NormItemId], [ControlId], [ReasonId]) VALUES (1, 10, NULL, NULL, NULL, NULL, NULL, NULL)
INSERT INTO [dbo].[ReportValues] ([ReportId], [NormItemId], [Note], [StatusId], [ReportValue_ReportId], [ReportValue_NormItemId], [ControlId], [ReasonId]) VALUES (1, 11, NULL, NULL, 1, 10, NULL, NULL)
INSERT INTO [dbo].[ReportValues] ([ReportId], [NormItemId], [Note], [StatusId], [ReportValue_ReportId], [ReportValue_NormItemId], [ControlId], [ReasonId]) VALUES (1, 12, N'Napomena test', 1, 1, 11, NULL, NULL)
INSERT INTO [dbo].[ReportValues] ([ReportId], [NormItemId], [Note], [StatusId], [ReportValue_ReportId], [ReportValue_NormItemId], [ControlId], [ReasonId]) VALUES (1, 13, N'Napomena test', 1, 1, 11, NULL, NULL)
INSERT INTO [dbo].[ReportValues] ([ReportId], [NormItemId], [Note], [StatusId], [ReportValue_ReportId], [ReportValue_NormItemId], [ControlId], [ReasonId]) VALUES (1, 14, N'Napomena test', 1, 1, 11, NULL, NULL)
INSERT INTO [dbo].[ReportValues] ([ReportId], [NormItemId], [Note], [StatusId], [ReportValue_ReportId], [ReportValue_NormItemId], [ControlId], [ReasonId]) VALUES (1, 15, N'Napomena test', 1, 1, 10, NULL, NULL)
INSERT INTO [dbo].[ReportValues] ([ReportId], [NormItemId], [Note], [StatusId], [ReportValue_ReportId], [ReportValue_NormItemId], [ControlId], [ReasonId]) VALUES (1, 16, NULL, NULL, NULL, NULL, NULL, NULL)
INSERT INTO [dbo].[ReportValues] ([ReportId], [NormItemId], [Note], [StatusId], [ReportValue_ReportId], [ReportValue_NormItemId], [ControlId], [ReasonId]) VALUES (1, 17, N'Napomena test', 1, 1, 16, NULL, NULL)
INSERT INTO [dbo].[ReportValues] ([ReportId], [NormItemId], [Note], [StatusId], [ReportValue_ReportId], [ReportValue_NormItemId], [ControlId], [ReasonId]) VALUES (1, 18, N'Napomena test', 1, 1, 16, NULL, NULL)
INSERT INTO [dbo].[ReportValues] ([ReportId], [NormItemId], [Note], [StatusId], [ReportValue_ReportId], [ReportValue_NormItemId], [ControlId], [ReasonId]) VALUES (1, 19, N'Napomena test', 1, 1, 16, NULL, NULL)
INSERT INTO [dbo].[ReportValues] ([ReportId], [NormItemId], [Note], [StatusId], [ReportValue_ReportId], [ReportValue_NormItemId], [ControlId], [ReasonId]) VALUES (1, 20, N'Napomena test', 1, 1, 16, NULL, NULL)
INSERT INTO [dbo].[ReportValues] ([ReportId], [NormItemId], [Note], [StatusId], [ReportValue_ReportId], [ReportValue_NormItemId], [ControlId], [ReasonId]) VALUES (1, 21, NULL, NULL, 1, 16, NULL, NULL)
INSERT INTO [dbo].[ReportValues] ([ReportId], [NormItemId], [Note], [StatusId], [ReportValue_ReportId], [ReportValue_NormItemId], [ControlId], [ReasonId]) VALUES (1, 22, N'Napomena test', 1, 1, 21, NULL, NULL)
INSERT INTO [dbo].[ReportValues] ([ReportId], [NormItemId], [Note], [StatusId], [ReportValue_ReportId], [ReportValue_NormItemId], [ControlId], [ReasonId]) VALUES (1, 23, N'Napomena test', 1, 1, 21, NULL, NULL)
INSERT INTO [dbo].[ReportValues] ([ReportId], [NormItemId], [Note], [StatusId], [ReportValue_ReportId], [ReportValue_NormItemId], [ControlId], [ReasonId]) VALUES (1, 24, N'Napomena test', 1, 1, 21, NULL, NULL)
INSERT INTO [dbo].[ReportValues] ([ReportId], [NormItemId], [Note], [StatusId], [ReportValue_ReportId], [ReportValue_NormItemId], [ControlId], [ReasonId]) VALUES (1, 25, NULL, NULL, NULL, NULL, NULL, NULL)
INSERT INTO [dbo].[ReportValues] ([ReportId], [NormItemId], [Note], [StatusId], [ReportValue_ReportId], [ReportValue_NormItemId], [ControlId], [ReasonId]) VALUES (1, 26, N'Napomena test', 1, 1, 25, NULL, NULL)
INSERT INTO [dbo].[ReportValues] ([ReportId], [NormItemId], [Note], [StatusId], [ReportValue_ReportId], [ReportValue_NormItemId], [ControlId], [ReasonId]) VALUES (1, 27, N'Napomena test', 1, 1, 25, NULL, NULL)
INSERT INTO [dbo].[ReportValues] ([ReportId], [NormItemId], [Note], [StatusId], [ReportValue_ReportId], [ReportValue_NormItemId], [ControlId], [ReasonId]) VALUES (1, 28, N'Napomena test', 1, 1, 25, NULL, NULL)
INSERT INTO [dbo].[ReportValues] ([ReportId], [NormItemId], [Note], [StatusId], [ReportValue_ReportId], [ReportValue_NormItemId], [ControlId], [ReasonId]) VALUES (1, 29, NULL, NULL, NULL, NULL, NULL, NULL)
INSERT INTO [dbo].[ReportValues] ([ReportId], [NormItemId], [Note], [StatusId], [ReportValue_ReportId], [ReportValue_NormItemId], [ControlId], [ReasonId]) VALUES (1, 30, N'Napomena test', 1, 1, 29, NULL, NULL)
INSERT INTO [dbo].[ReportValues] ([ReportId], [NormItemId], [Note], [StatusId], [ReportValue_ReportId], [ReportValue_NormItemId], [ControlId], [ReasonId]) VALUES (1, 31, N'Napomena test', 1, 1, 29, NULL, NULL)
INSERT INTO [dbo].[ReportValues] ([ReportId], [NormItemId], [Note], [StatusId], [ReportValue_ReportId], [ReportValue_NormItemId], [ControlId], [ReasonId]) VALUES (1, 32, N'Napomena test', 1, 1, 29, NULL, NULL)
INSERT INTO [dbo].[ReportValues] ([ReportId], [NormItemId], [Note], [StatusId], [ReportValue_ReportId], [ReportValue_NormItemId], [ControlId], [ReasonId]) VALUES (1, 33, NULL, NULL, NULL, NULL, NULL, NULL)
INSERT INTO [dbo].[ReportValues] ([ReportId], [NormItemId], [Note], [StatusId], [ReportValue_ReportId], [ReportValue_NormItemId], [ControlId], [ReasonId]) VALUES (1, 34, N'Napomena test', 1, 1, 33, NULL, NULL)
INSERT INTO [dbo].[ReportValues] ([ReportId], [NormItemId], [Note], [StatusId], [ReportValue_ReportId], [ReportValue_NormItemId], [ControlId], [ReasonId]) VALUES (1, 35, N'Napomena test', 1, 1, 33, NULL, NULL)
INSERT INTO [dbo].[ReportValues] ([ReportId], [NormItemId], [Note], [StatusId], [ReportValue_ReportId], [ReportValue_NormItemId], [ControlId], [ReasonId]) VALUES (2, 36, NULL, NULL, NULL, NULL, NULL, NULL)
INSERT INTO [dbo].[ReportValues] ([ReportId], [NormItemId], [Note], [StatusId], [ReportValue_ReportId], [ReportValue_NormItemId], [ControlId], [ReasonId]) VALUES (2, 37, NULL, NULL, 2, 36, NULL, NULL)
INSERT INTO [dbo].[ReportValues] ([ReportId], [NormItemId], [Note], [StatusId], [ReportValue_ReportId], [ReportValue_NormItemId], [ControlId], [ReasonId]) VALUES (2, 38, N'Napomena test', 1, 2, 37, 1, 1)
INSERT INTO [dbo].[ReportValues] ([ReportId], [NormItemId], [Note], [StatusId], [ReportValue_ReportId], [ReportValue_NormItemId], [ControlId], [ReasonId]) VALUES (2, 39, N'Napomena test', 1, 2, 37, 1, 1)
INSERT INTO [dbo].[ReportValues] ([ReportId], [NormItemId], [Note], [StatusId], [ReportValue_ReportId], [ReportValue_NormItemId], [ControlId], [ReasonId]) VALUES (2, 40, NULL, NULL, NULL, NULL, NULL, NULL)
INSERT INTO [dbo].[ReportValues] ([ReportId], [NormItemId], [Note], [StatusId], [ReportValue_ReportId], [ReportValue_NormItemId], [ControlId], [ReasonId]) VALUES (2, 41, NULL, NULL, 2, 40, NULL, NULL)
INSERT INTO [dbo].[ReportValues] ([ReportId], [NormItemId], [Note], [StatusId], [ReportValue_ReportId], [ReportValue_NormItemId], [ControlId], [ReasonId]) VALUES (2, 42, N'Napomena test', 1, 2, 41, 1, 1)
INSERT INTO [dbo].[ReportValues] ([ReportId], [NormItemId], [Note], [StatusId], [ReportValue_ReportId], [ReportValue_NormItemId], [ControlId], [ReasonId]) VALUES (2, 43, N'Napomena test', 1, 2, 41, 1, 1)
INSERT INTO [dbo].[ReportValues] ([ReportId], [NormItemId], [Note], [StatusId], [ReportValue_ReportId], [ReportValue_NormItemId], [ControlId], [ReasonId]) VALUES (2, 44, N'Napomena test', 1, 2, 41, 1, 1)
INSERT INTO [dbo].[ReportValues] ([ReportId], [NormItemId], [Note], [StatusId], [ReportValue_ReportId], [ReportValue_NormItemId], [ControlId], [ReasonId]) VALUES (2, 45, N'Napomena test', 1, 2, 41, 1, 1)
INSERT INTO [dbo].[ReportValues] ([ReportId], [NormItemId], [Note], [StatusId], [ReportValue_ReportId], [ReportValue_NormItemId], [ControlId], [ReasonId]) VALUES (2, 46, N'Napomena test', 1, 2, 41, 1, 1)
INSERT INTO [dbo].[ReportValues] ([ReportId], [NormItemId], [Note], [StatusId], [ReportValue_ReportId], [ReportValue_NormItemId], [ControlId], [ReasonId]) VALUES (2, 47, NULL, NULL, 2, 40, NULL, NULL)
INSERT INTO [dbo].[ReportValues] ([ReportId], [NormItemId], [Note], [StatusId], [ReportValue_ReportId], [ReportValue_NormItemId], [ControlId], [ReasonId]) VALUES (2, 48, N'Napomena test', 1, 2, 47, 1, 1)
INSERT INTO [dbo].[ReportValues] ([ReportId], [NormItemId], [Note], [StatusId], [ReportValue_ReportId], [ReportValue_NormItemId], [ControlId], [ReasonId]) VALUES (2, 49, N'Napomena test', 1, 2, 47, 1, 1)
INSERT INTO [dbo].[ReportValues] ([ReportId], [NormItemId], [Note], [StatusId], [ReportValue_ReportId], [ReportValue_NormItemId], [ControlId], [ReasonId]) VALUES (2, 50, NULL, NULL, NULL, NULL, NULL, NULL)
INSERT INTO [dbo].[ReportValues] ([ReportId], [NormItemId], [Note], [StatusId], [ReportValue_ReportId], [ReportValue_NormItemId], [ControlId], [ReasonId]) VALUES (2, 51, NULL, NULL, 2, 50, NULL, NULL)
INSERT INTO [dbo].[ReportValues] ([ReportId], [NormItemId], [Note], [StatusId], [ReportValue_ReportId], [ReportValue_NormItemId], [ControlId], [ReasonId]) VALUES (2, 52, N'Napomena test', 1, 2, 51, 1, 1)
INSERT INTO [dbo].[ReportValues] ([ReportId], [NormItemId], [Note], [StatusId], [ReportValue_ReportId], [ReportValue_NormItemId], [ControlId], [ReasonId]) VALUES (2, 53, N'Napomena test', 1, 2, 51, 1, 1)
INSERT INTO [dbo].[ReportValues] ([ReportId], [NormItemId], [Note], [StatusId], [ReportValue_ReportId], [ReportValue_NormItemId], [ControlId], [ReasonId]) VALUES (2, 54, NULL, NULL, 2, 50, NULL, NULL)
INSERT INTO [dbo].[ReportValues] ([ReportId], [NormItemId], [Note], [StatusId], [ReportValue_ReportId], [ReportValue_NormItemId], [ControlId], [ReasonId]) VALUES (2, 55, N'Napomena test', 1, 2, 54, 1, 1)
INSERT INTO [dbo].[ReportValues] ([ReportId], [NormItemId], [Note], [StatusId], [ReportValue_ReportId], [ReportValue_NormItemId], [ControlId], [ReasonId]) VALUES (2, 56, N'Napomena test', 1, 2, 54, 1, 1)
INSERT INTO [dbo].[ReportValues] ([ReportId], [NormItemId], [Note], [StatusId], [ReportValue_ReportId], [ReportValue_NormItemId], [ControlId], [ReasonId]) VALUES (2, 57, N'Napomena test', 1, 2, 54, 1, 1)
INSERT INTO [dbo].[ReportValues] ([ReportId], [NormItemId], [Note], [StatusId], [ReportValue_ReportId], [ReportValue_NormItemId], [ControlId], [ReasonId]) VALUES (2, 58, NULL, NULL, 2, 50, NULL, NULL)
INSERT INTO [dbo].[ReportValues] ([ReportId], [NormItemId], [Note], [StatusId], [ReportValue_ReportId], [ReportValue_NormItemId], [ControlId], [ReasonId]) VALUES (2, 59, N'Napomena test', 1, 2, 58, 1, 1)
INSERT INTO [dbo].[ReportValues] ([ReportId], [NormItemId], [Note], [StatusId], [ReportValue_ReportId], [ReportValue_NormItemId], [ControlId], [ReasonId]) VALUES (2, 60, NULL, NULL, NULL, NULL, NULL, NULL)
INSERT INTO [dbo].[ReportValues] ([ReportId], [NormItemId], [Note], [StatusId], [ReportValue_ReportId], [ReportValue_NormItemId], [ControlId], [ReasonId]) VALUES (2, 61, NULL, NULL, 2, 60, NULL, NULL)
INSERT INTO [dbo].[ReportValues] ([ReportId], [NormItemId], [Note], [StatusId], [ReportValue_ReportId], [ReportValue_NormItemId], [ControlId], [ReasonId]) VALUES (2, 62, N'Napomena test', 1, 2, 61, 1, 1)
INSERT INTO [dbo].[ReportValues] ([ReportId], [NormItemId], [Note], [StatusId], [ReportValue_ReportId], [ReportValue_NormItemId], [ControlId], [ReasonId]) VALUES (2, 63, N'Napomena test', 1, 2, 61, 1, 1)
INSERT INTO [dbo].[ReportValues] ([ReportId], [NormItemId], [Note], [StatusId], [ReportValue_ReportId], [ReportValue_NormItemId], [ControlId], [ReasonId]) VALUES (2, 64, N'Napomena test', 1, 2, 61, 1, 1)
INSERT INTO [dbo].[ReportValues] ([ReportId], [NormItemId], [Note], [StatusId], [ReportValue_ReportId], [ReportValue_NormItemId], [ControlId], [ReasonId]) VALUES (2, 65, N'Napomena test', 1, 2, 61, 1, 1)
INSERT INTO [dbo].[ReportValues] ([ReportId], [NormItemId], [Note], [StatusId], [ReportValue_ReportId], [ReportValue_NormItemId], [ControlId], [ReasonId]) VALUES (2, 66, NULL, NULL, 2, 60, NULL, NULL)
INSERT INTO [dbo].[ReportValues] ([ReportId], [NormItemId], [Note], [StatusId], [ReportValue_ReportId], [ReportValue_NormItemId], [ControlId], [ReasonId]) VALUES (2, 67, N'Napomena test', 1, 2, 66, 1, 1)
INSERT INTO [dbo].[ReportValues] ([ReportId], [NormItemId], [Note], [StatusId], [ReportValue_ReportId], [ReportValue_NormItemId], [ControlId], [ReasonId]) VALUES (2, 68, N'Napomena test', 1, 2, 66, 1, 1)
INSERT INTO [dbo].[ReportValues] ([ReportId], [NormItemId], [Note], [StatusId], [ReportValue_ReportId], [ReportValue_NormItemId], [ControlId], [ReasonId]) VALUES (2, 69, N'Napomena test', 1, 2, 66, 1, 1)
INSERT INTO [dbo].[ReportValues] ([ReportId], [NormItemId], [Note], [StatusId], [ReportValue_ReportId], [ReportValue_NormItemId], [ControlId], [ReasonId]) VALUES (2, 70, NULL, NULL, 2, 60, NULL, NULL)
INSERT INTO [dbo].[ReportValues] ([ReportId], [NormItemId], [Note], [StatusId], [ReportValue_ReportId], [ReportValue_NormItemId], [ControlId], [ReasonId]) VALUES (2, 71, N'Napomena test', 1, 2, 70, 1, 1)
INSERT INTO [dbo].[ReportValues] ([ReportId], [NormItemId], [Note], [StatusId], [ReportValue_ReportId], [ReportValue_NormItemId], [ControlId], [ReasonId]) VALUES (2, 72, N'Napomena test', 1, 2, 70, 1, 1)
INSERT INTO [dbo].[ReportValues] ([ReportId], [NormItemId], [Note], [StatusId], [ReportValue_ReportId], [ReportValue_NormItemId], [ControlId], [ReasonId]) VALUES (2, 73, N'Napomena test', 1, 2, 70, 1, 1)
INSERT INTO [dbo].[ReportValues] ([ReportId], [NormItemId], [Note], [StatusId], [ReportValue_ReportId], [ReportValue_NormItemId], [ControlId], [ReasonId]) VALUES (2, 74, NULL, NULL, NULL, NULL, NULL, NULL)
INSERT INTO [dbo].[ReportValues] ([ReportId], [NormItemId], [Note], [StatusId], [ReportValue_ReportId], [ReportValue_NormItemId], [ControlId], [ReasonId]) VALUES (2, 75, NULL, NULL, 2, 74, NULL, NULL)
INSERT INTO [dbo].[ReportValues] ([ReportId], [NormItemId], [Note], [StatusId], [ReportValue_ReportId], [ReportValue_NormItemId], [ControlId], [ReasonId]) VALUES (2, 76, N'Napomena test', 1, 2, 75, 1, 1)
INSERT INTO [dbo].[ReportValues] ([ReportId], [NormItemId], [Note], [StatusId], [ReportValue_ReportId], [ReportValue_NormItemId], [ControlId], [ReasonId]) VALUES (2, 77, N'Napomena test', 1, 2, 75, 1, 1)
INSERT INTO [dbo].[ReportValues] ([ReportId], [NormItemId], [Note], [StatusId], [ReportValue_ReportId], [ReportValue_NormItemId], [ControlId], [ReasonId]) VALUES (2, 78, NULL, NULL, 2, 74, NULL, NULL)
INSERT INTO [dbo].[ReportValues] ([ReportId], [NormItemId], [Note], [StatusId], [ReportValue_ReportId], [ReportValue_NormItemId], [ControlId], [ReasonId]) VALUES (2, 79, N'Napomena test', 1, 2, 78, 1, 1)
INSERT INTO [dbo].[ReportValues] ([ReportId], [NormItemId], [Note], [StatusId], [ReportValue_ReportId], [ReportValue_NormItemId], [ControlId], [ReasonId]) VALUES (2, 80, N'Napomena test', 1, 2, 78, 1, 1)
INSERT INTO [dbo].[ReportValues] ([ReportId], [NormItemId], [Note], [StatusId], [ReportValue_ReportId], [ReportValue_NormItemId], [ControlId], [ReasonId]) VALUES (2, 81, N'Napomena test', 1, 2, 78, 1, 1)
INSERT INTO [dbo].[ReportValues] ([ReportId], [NormItemId], [Note], [StatusId], [ReportValue_ReportId], [ReportValue_NormItemId], [ControlId], [ReasonId]) VALUES (2, 82, N'Napomena test', 1, 2, 78, 1, 1)
INSERT INTO [dbo].[ReportValues] ([ReportId], [NormItemId], [Note], [StatusId], [ReportValue_ReportId], [ReportValue_NormItemId], [ControlId], [ReasonId]) VALUES (2, 83, N'Napomena test', 1, 2, 78, 1, 1)
INSERT INTO [dbo].[ReportValues] ([ReportId], [NormItemId], [Note], [StatusId], [ReportValue_ReportId], [ReportValue_NormItemId], [ControlId], [ReasonId]) VALUES (2, 84, N'Napomena test', 1, 2, 78, 1, 1)
INSERT INTO [dbo].[ReportValues] ([ReportId], [NormItemId], [Note], [StatusId], [ReportValue_ReportId], [ReportValue_NormItemId], [ControlId], [ReasonId]) VALUES (2, 85, NULL, NULL, 2, 74, NULL, NULL)
INSERT INTO [dbo].[ReportValues] ([ReportId], [NormItemId], [Note], [StatusId], [ReportValue_ReportId], [ReportValue_NormItemId], [ControlId], [ReasonId]) VALUES (2, 86, N'Napomena test', 1, 2, 85, 1, 1)
INSERT INTO [dbo].[ReportValues] ([ReportId], [NormItemId], [Note], [StatusId], [ReportValue_ReportId], [ReportValue_NormItemId], [ControlId], [ReasonId]) VALUES (2, 87, NULL, NULL, 2, 74, NULL, NULL)
INSERT INTO [dbo].[ReportValues] ([ReportId], [NormItemId], [Note], [StatusId], [ReportValue_ReportId], [ReportValue_NormItemId], [ControlId], [ReasonId]) VALUES (2, 88, N'Napomena test', 1, 2, 87, 1, 1)
INSERT INTO [dbo].[ReportValues] ([ReportId], [NormItemId], [Note], [StatusId], [ReportValue_ReportId], [ReportValue_NormItemId], [ControlId], [ReasonId]) VALUES (2, 89, N'Napomena test', 1, 2, 87, 1, 1)
INSERT INTO [dbo].[ReportValues] ([ReportId], [NormItemId], [Note], [StatusId], [ReportValue_ReportId], [ReportValue_NormItemId], [ControlId], [ReasonId]) VALUES (2, 90, N'Napomena test', 1, 2, 87, 1, 1)
INSERT INTO [dbo].[ReportValues] ([ReportId], [NormItemId], [Note], [StatusId], [ReportValue_ReportId], [ReportValue_NormItemId], [ControlId], [ReasonId]) VALUES (2, 91, N'Napomena test', 1, 2, 87, 1, 1)
INSERT INTO [dbo].[ReportValues] ([ReportId], [NormItemId], [Note], [StatusId], [ReportValue_ReportId], [ReportValue_NormItemId], [ControlId], [ReasonId]) VALUES (2, 92, N'Napomena test', 1, 2, 87, 1, 1)
INSERT INTO [dbo].[ReportValues] ([ReportId], [NormItemId], [Note], [StatusId], [ReportValue_ReportId], [ReportValue_NormItemId], [ControlId], [ReasonId]) VALUES (2, 93, NULL, NULL, NULL, NULL, NULL, NULL)
INSERT INTO [dbo].[ReportValues] ([ReportId], [NormItemId], [Note], [StatusId], [ReportValue_ReportId], [ReportValue_NormItemId], [ControlId], [ReasonId]) VALUES (2, 94, NULL, NULL, 2, 93, NULL, NULL)
INSERT INTO [dbo].[ReportValues] ([ReportId], [NormItemId], [Note], [StatusId], [ReportValue_ReportId], [ReportValue_NormItemId], [ControlId], [ReasonId]) VALUES (2, 95, N'Napomena test', 1, 2, 94, 1, 1)
INSERT INTO [dbo].[ReportValues] ([ReportId], [NormItemId], [Note], [StatusId], [ReportValue_ReportId], [ReportValue_NormItemId], [ControlId], [ReasonId]) VALUES (2, 96, N'Napomena test', 1, 2, 94, 1, 1)
INSERT INTO [dbo].[ReportValues] ([ReportId], [NormItemId], [Note], [StatusId], [ReportValue_ReportId], [ReportValue_NormItemId], [ControlId], [ReasonId]) VALUES (2, 97, NULL, NULL, NULL, NULL, NULL, NULL)
INSERT INTO [dbo].[ReportValues] ([ReportId], [NormItemId], [Note], [StatusId], [ReportValue_ReportId], [ReportValue_NormItemId], [ControlId], [ReasonId]) VALUES (2, 98, NULL, NULL, 2, 97, NULL, NULL)
INSERT INTO [dbo].[ReportValues] ([ReportId], [NormItemId], [Note], [StatusId], [ReportValue_ReportId], [ReportValue_NormItemId], [ControlId], [ReasonId]) VALUES (2, 99, N'Napomena test', 1, 2, 98, 1, 1)
INSERT INTO [dbo].[ReportValues] ([ReportId], [NormItemId], [Note], [StatusId], [ReportValue_ReportId], [ReportValue_NormItemId], [ControlId], [ReasonId]) VALUES (2, 100, N'Napomena test', 1, 2, 98, 1, 1)
INSERT INTO [dbo].[ReportValues] ([ReportId], [NormItemId], [Note], [StatusId], [ReportValue_ReportId], [ReportValue_NormItemId], [ControlId], [ReasonId]) VALUES (2, 101, N'Napomena test', 1, 2, 98, 1, 1)
INSERT INTO [dbo].[ReportValues] ([ReportId], [NormItemId], [Note], [StatusId], [ReportValue_ReportId], [ReportValue_NormItemId], [ControlId], [ReasonId]) VALUES (2, 102, N'Napomena test', 1, 2, 98, 1, 1)
INSERT INTO [dbo].[ReportValues] ([ReportId], [NormItemId], [Note], [StatusId], [ReportValue_ReportId], [ReportValue_NormItemId], [ControlId], [ReasonId]) VALUES (2, 103, N'Napomena test', 1, 2, 98, 1, 1)
INSERT INTO [dbo].[ReportValues] ([ReportId], [NormItemId], [Note], [StatusId], [ReportValue_ReportId], [ReportValue_NormItemId], [ControlId], [ReasonId]) VALUES (2, 104, N'Napomena test', 1, 2, 98, 1, 1)
INSERT INTO [dbo].[ReportValues] ([ReportId], [NormItemId], [Note], [StatusId], [ReportValue_ReportId], [ReportValue_NormItemId], [ControlId], [ReasonId]) VALUES (2, 105, NULL, NULL, 2, 97, NULL, NULL)
INSERT INTO [dbo].[ReportValues] ([ReportId], [NormItemId], [Note], [StatusId], [ReportValue_ReportId], [ReportValue_NormItemId], [ControlId], [ReasonId]) VALUES (2, 106, N'Napomena test', 1, 2, 105, 1, 1)
INSERT INTO [dbo].[ReportValues] ([ReportId], [NormItemId], [Note], [StatusId], [ReportValue_ReportId], [ReportValue_NormItemId], [ControlId], [ReasonId]) VALUES (2, 107, N'Napomena test', 1, 2, 105, 1, 1)
INSERT INTO [dbo].[ReportValues] ([ReportId], [NormItemId], [Note], [StatusId], [ReportValue_ReportId], [ReportValue_NormItemId], [ControlId], [ReasonId]) VALUES (2, 108, N'Napomena test', 1, 2, 105, 1, 1)
INSERT INTO [dbo].[ReportValues] ([ReportId], [NormItemId], [Note], [StatusId], [ReportValue_ReportId], [ReportValue_NormItemId], [ControlId], [ReasonId]) VALUES (2, 109, N'Napomena test', 1, 2, 105, 1, 1)
INSERT INTO [dbo].[ReportValues] ([ReportId], [NormItemId], [Note], [StatusId], [ReportValue_ReportId], [ReportValue_NormItemId], [ControlId], [ReasonId]) VALUES (2, 110, N'Napomena test', 1, 2, 105, 1, 1)
INSERT INTO [dbo].[ReportValues] ([ReportId], [NormItemId], [Note], [StatusId], [ReportValue_ReportId], [ReportValue_NormItemId], [ControlId], [ReasonId]) VALUES (2, 111, N'Napomena test', 1, 2, 105, 1, 1)
INSERT INTO [dbo].[ReportValues] ([ReportId], [NormItemId], [Note], [StatusId], [ReportValue_ReportId], [ReportValue_NormItemId], [ControlId], [ReasonId]) VALUES (2, 112, N'Napomena test', 1, 2, 105, 1, 1)
INSERT INTO [dbo].[ReportValues] ([ReportId], [NormItemId], [Note], [StatusId], [ReportValue_ReportId], [ReportValue_NormItemId], [ControlId], [ReasonId]) VALUES (2, 113, N'Napomena test', 1, 2, 105, 1, 1)
INSERT INTO [dbo].[ReportValues] ([ReportId], [NormItemId], [Note], [StatusId], [ReportValue_ReportId], [ReportValue_NormItemId], [ControlId], [ReasonId]) VALUES (2, 114, N'Napomena test', 1, 2, 105, 1, 1)
INSERT INTO [dbo].[ReportValues] ([ReportId], [NormItemId], [Note], [StatusId], [ReportValue_ReportId], [ReportValue_NormItemId], [ControlId], [ReasonId]) VALUES (2, 115, NULL, NULL, NULL, NULL, NULL, NULL)
INSERT INTO [dbo].[ReportValues] ([ReportId], [NormItemId], [Note], [StatusId], [ReportValue_ReportId], [ReportValue_NormItemId], [ControlId], [ReasonId]) VALUES (2, 116, NULL, NULL, 2, 115, NULL, NULL)
INSERT INTO [dbo].[ReportValues] ([ReportId], [NormItemId], [Note], [StatusId], [ReportValue_ReportId], [ReportValue_NormItemId], [ControlId], [ReasonId]) VALUES (2, 117, N'Napomena test', 1, 2, 116, 1, 1)
INSERT INTO [dbo].[ReportValues] ([ReportId], [NormItemId], [Note], [StatusId], [ReportValue_ReportId], [ReportValue_NormItemId], [ControlId], [ReasonId]) VALUES (2, 118, N'Napomena test', 1, 2, 116, 1, 1)
INSERT INTO [dbo].[ReportValues] ([ReportId], [NormItemId], [Note], [StatusId], [ReportValue_ReportId], [ReportValue_NormItemId], [ControlId], [ReasonId]) VALUES (2, 119, N'Napomena test', 1, 2, 116, 1, 1)
INSERT INTO [dbo].[ReportValues] ([ReportId], [NormItemId], [Note], [StatusId], [ReportValue_ReportId], [ReportValue_NormItemId], [ControlId], [ReasonId]) VALUES (2, 120, N'Napomena test', 1, 2, 116, 1, 1)
INSERT INTO [dbo].[ReportValues] ([ReportId], [NormItemId], [Note], [StatusId], [ReportValue_ReportId], [ReportValue_NormItemId], [ControlId], [ReasonId]) VALUES (2, 121, NULL, NULL, 2, 115, NULL, NULL)
INSERT INTO [dbo].[ReportValues] ([ReportId], [NormItemId], [Note], [StatusId], [ReportValue_ReportId], [ReportValue_NormItemId], [ControlId], [ReasonId]) VALUES (2, 122, N'Napomena test', 1, 2, 121, 1, 1)
INSERT INTO [dbo].[ReportValues] ([ReportId], [NormItemId], [Note], [StatusId], [ReportValue_ReportId], [ReportValue_NormItemId], [ControlId], [ReasonId]) VALUES (2, 123, NULL, NULL, 2, 115, NULL, NULL)
INSERT INTO [dbo].[ReportValues] ([ReportId], [NormItemId], [Note], [StatusId], [ReportValue_ReportId], [ReportValue_NormItemId], [ControlId], [ReasonId]) VALUES (2, 124, N'Napomena test', 1, 2, 123, 1, 1)
INSERT INTO [dbo].[ReportValues] ([ReportId], [NormItemId], [Note], [StatusId], [ReportValue_ReportId], [ReportValue_NormItemId], [ControlId], [ReasonId]) VALUES (2, 125, NULL, NULL, 2, 115, NULL, NULL)
INSERT INTO [dbo].[ReportValues] ([ReportId], [NormItemId], [Note], [StatusId], [ReportValue_ReportId], [ReportValue_NormItemId], [ControlId], [ReasonId]) VALUES (2, 126, N'Napomena test', 1, 2, 125, 1, 1)
INSERT INTO [dbo].[ReportValues] ([ReportId], [NormItemId], [Note], [StatusId], [ReportValue_ReportId], [ReportValue_NormItemId], [ControlId], [ReasonId]) VALUES (2, 127, N'Napomena test', 1, 2, 125, 1, 1)
INSERT INTO [dbo].[ReportValues] ([ReportId], [NormItemId], [Note], [StatusId], [ReportValue_ReportId], [ReportValue_NormItemId], [ControlId], [ReasonId]) VALUES (2, 128, N'Napomena test', 1, 2, 125, 1, 1)
INSERT INTO [dbo].[ReportValues] ([ReportId], [NormItemId], [Note], [StatusId], [ReportValue_ReportId], [ReportValue_NormItemId], [ControlId], [ReasonId]) VALUES (2, 129, N'Napomena test', 1, 2, 125, 1, 1)
INSERT INTO [dbo].[ReportValues] ([ReportId], [NormItemId], [Note], [StatusId], [ReportValue_ReportId], [ReportValue_NormItemId], [ControlId], [ReasonId]) VALUES (2, 130, NULL, NULL, 2, 115, NULL, NULL)
INSERT INTO [dbo].[ReportValues] ([ReportId], [NormItemId], [Note], [StatusId], [ReportValue_ReportId], [ReportValue_NormItemId], [ControlId], [ReasonId]) VALUES (2, 131, N'Napomena test', 1, 2, 130, 1, 1)
INSERT INTO [dbo].[ReportValues] ([ReportId], [NormItemId], [Note], [StatusId], [ReportValue_ReportId], [ReportValue_NormItemId], [ControlId], [ReasonId]) VALUES (2, 132, NULL, NULL, 2, 115, NULL, NULL)
INSERT INTO [dbo].[ReportValues] ([ReportId], [NormItemId], [Note], [StatusId], [ReportValue_ReportId], [ReportValue_NormItemId], [ControlId], [ReasonId]) VALUES (2, 133, N'Napomena test', 1, 2, 132, 1, 1)
INSERT INTO [dbo].[ReportValues] ([ReportId], [NormItemId], [Note], [StatusId], [ReportValue_ReportId], [ReportValue_NormItemId], [ControlId], [ReasonId]) VALUES (2, 134, N'Napomena test', 1, 2, 132, 1, 1)
INSERT INTO [dbo].[ReportValues] ([ReportId], [NormItemId], [Note], [StatusId], [ReportValue_ReportId], [ReportValue_NormItemId], [ControlId], [ReasonId]) VALUES (2, 135, NULL, NULL, 2, 115, NULL, NULL)
INSERT INTO [dbo].[ReportValues] ([ReportId], [NormItemId], [Note], [StatusId], [ReportValue_ReportId], [ReportValue_NormItemId], [ControlId], [ReasonId]) VALUES (2, 136, N'Napomena test', 1, 2, 135, 1, 1)
INSERT INTO [dbo].[ReportValues] ([ReportId], [NormItemId], [Note], [StatusId], [ReportValue_ReportId], [ReportValue_NormItemId], [ControlId], [ReasonId]) VALUES (2, 137, NULL, NULL, NULL, NULL, NULL, NULL)
INSERT INTO [dbo].[ReportValues] ([ReportId], [NormItemId], [Note], [StatusId], [ReportValue_ReportId], [ReportValue_NormItemId], [ControlId], [ReasonId]) VALUES (2, 138, NULL, NULL, 2, 137, NULL, NULL)
INSERT INTO [dbo].[ReportValues] ([ReportId], [NormItemId], [Note], [StatusId], [ReportValue_ReportId], [ReportValue_NormItemId], [ControlId], [ReasonId]) VALUES (2, 139, N'Napomena test', 1, 2, 138, 1, 1)
INSERT INTO [dbo].[ReportValues] ([ReportId], [NormItemId], [Note], [StatusId], [ReportValue_ReportId], [ReportValue_NormItemId], [ControlId], [ReasonId]) VALUES (2, 140, N'Napomena test', 1, 2, 138, 1, 1)
INSERT INTO [dbo].[ReportValues] ([ReportId], [NormItemId], [Note], [StatusId], [ReportValue_ReportId], [ReportValue_NormItemId], [ControlId], [ReasonId]) VALUES (2, 141, N'Napomena test', 1, 2, 138, 1, 1)
INSERT INTO [dbo].[ReportValues] ([ReportId], [NormItemId], [Note], [StatusId], [ReportValue_ReportId], [ReportValue_NormItemId], [ControlId], [ReasonId]) VALUES (2, 142, NULL, NULL, 2, 137, NULL, NULL)
INSERT INTO [dbo].[ReportValues] ([ReportId], [NormItemId], [Note], [StatusId], [ReportValue_ReportId], [ReportValue_NormItemId], [ControlId], [ReasonId]) VALUES (2, 143, N'Napomena test', 1, 2, 142, 1, 1)
INSERT INTO [dbo].[ReportValues] ([ReportId], [NormItemId], [Note], [StatusId], [ReportValue_ReportId], [ReportValue_NormItemId], [ControlId], [ReasonId]) VALUES (2, 144, N'Napomena test', 1, 2, 142, 1, 1)
INSERT INTO [dbo].[ReportValues] ([ReportId], [NormItemId], [Note], [StatusId], [ReportValue_ReportId], [ReportValue_NormItemId], [ControlId], [ReasonId]) VALUES (2, 145, N'Napomena test', 1, 2, 142, 1, 1)
INSERT INTO [dbo].[ReportValues] ([ReportId], [NormItemId], [Note], [StatusId], [ReportValue_ReportId], [ReportValue_NormItemId], [ControlId], [ReasonId]) VALUES (2, 146, N'Napomena test', 1, 2, 142, 1, 1)
INSERT INTO [dbo].[ReportValues] ([ReportId], [NormItemId], [Note], [StatusId], [ReportValue_ReportId], [ReportValue_NormItemId], [ControlId], [ReasonId]) VALUES (2, 147, NULL, NULL, NULL, NULL, NULL, NULL)
INSERT INTO [dbo].[ReportValues] ([ReportId], [NormItemId], [Note], [StatusId], [ReportValue_ReportId], [ReportValue_NormItemId], [ControlId], [ReasonId]) VALUES (2, 148, NULL, NULL, 2, 147, NULL, NULL)
INSERT INTO [dbo].[ReportValues] ([ReportId], [NormItemId], [Note], [StatusId], [ReportValue_ReportId], [ReportValue_NormItemId], [ControlId], [ReasonId]) VALUES (2, 149, N'Napomena test', 1, 2, 148, 1, 1)
INSERT INTO [dbo].[ReportValues] ([ReportId], [NormItemId], [Note], [StatusId], [ReportValue_ReportId], [ReportValue_NormItemId], [ControlId], [ReasonId]) VALUES (2, 150, N'Napomena test', 1, 2, 148, 1, 1)
INSERT INTO [dbo].[ReportValues] ([ReportId], [NormItemId], [Note], [StatusId], [ReportValue_ReportId], [ReportValue_NormItemId], [ControlId], [ReasonId]) VALUES (2, 151, N'Napomena test', 1, 2, 148, 1, 1)
INSERT INTO [dbo].[ReportValues] ([ReportId], [NormItemId], [Note], [StatusId], [ReportValue_ReportId], [ReportValue_NormItemId], [ControlId], [ReasonId]) VALUES (2, 152, NULL, NULL, 2, 147, NULL, NULL)
INSERT INTO [dbo].[ReportValues] ([ReportId], [NormItemId], [Note], [StatusId], [ReportValue_ReportId], [ReportValue_NormItemId], [ControlId], [ReasonId]) VALUES (2, 153, N'Napomena test', 1, 2, 152, 1, 1)
INSERT INTO [dbo].[ReportValues] ([ReportId], [NormItemId], [Note], [StatusId], [ReportValue_ReportId], [ReportValue_NormItemId], [ControlId], [ReasonId]) VALUES (2, 154, N'Napomena test', 1, 2, 152, 1, 1)
INSERT INTO [dbo].[ReportValues] ([ReportId], [NormItemId], [Note], [StatusId], [ReportValue_ReportId], [ReportValue_NormItemId], [ControlId], [ReasonId]) VALUES (2, 155, N'Napomena test', 1, 2, 152, 1, 1)
INSERT INTO [dbo].[ReportValues] ([ReportId], [NormItemId], [Note], [StatusId], [ReportValue_ReportId], [ReportValue_NormItemId], [ControlId], [ReasonId]) VALUES (2, 156, N'Napomena test', 1, 2, 152, 1, 1)
INSERT INTO [dbo].[ReportValues] ([ReportId], [NormItemId], [Note], [StatusId], [ReportValue_ReportId], [ReportValue_NormItemId], [ControlId], [ReasonId]) VALUES (2, 157, N'Napomena test', 1, 2, 152, 1, 1)
INSERT INTO [dbo].[ReportValues] ([ReportId], [NormItemId], [Note], [StatusId], [ReportValue_ReportId], [ReportValue_NormItemId], [ControlId], [ReasonId]) VALUES (2, 158, N'Napomena test', 1, 2, 152, 1, 1)
INSERT INTO [dbo].[ReportValues] ([ReportId], [NormItemId], [Note], [StatusId], [ReportValue_ReportId], [ReportValue_NormItemId], [ControlId], [ReasonId]) VALUES (2, 159, N'Napomena test', 1, 2, 152, 1, 1)
INSERT INTO [dbo].[ReportValues] ([ReportId], [NormItemId], [Note], [StatusId], [ReportValue_ReportId], [ReportValue_NormItemId], [ControlId], [ReasonId]) VALUES (2, 160, N'Napomena test', 1, 2, 152, 1, 1)
INSERT INTO [dbo].[ReportValues] ([ReportId], [NormItemId], [Note], [StatusId], [ReportValue_ReportId], [ReportValue_NormItemId], [ControlId], [ReasonId]) VALUES (2, 161, N'Napomena test', 1, 2, 152, 1, 1)
INSERT INTO [dbo].[ReportValues] ([ReportId], [NormItemId], [Note], [StatusId], [ReportValue_ReportId], [ReportValue_NormItemId], [ControlId], [ReasonId]) VALUES (2, 162, NULL, NULL, 2, 147, NULL, NULL)
INSERT INTO [dbo].[ReportValues] ([ReportId], [NormItemId], [Note], [StatusId], [ReportValue_ReportId], [ReportValue_NormItemId], [ControlId], [ReasonId]) VALUES (2, 163, N'Napomena test', 1, 2, 162, 1, 1)
INSERT INTO [dbo].[ReportValues] ([ReportId], [NormItemId], [Note], [StatusId], [ReportValue_ReportId], [ReportValue_NormItemId], [ControlId], [ReasonId]) VALUES (2, 164, NULL, NULL, NULL, NULL, NULL, NULL)
INSERT INTO [dbo].[ReportValues] ([ReportId], [NormItemId], [Note], [StatusId], [ReportValue_ReportId], [ReportValue_NormItemId], [ControlId], [ReasonId]) VALUES (2, 165, NULL, NULL, 2, 164, NULL, NULL)
INSERT INTO [dbo].[ReportValues] ([ReportId], [NormItemId], [Note], [StatusId], [ReportValue_ReportId], [ReportValue_NormItemId], [ControlId], [ReasonId]) VALUES (2, 166, N'Napomena test', 1, 2, 165, 1, 1)
INSERT INTO [dbo].[ReportValues] ([ReportId], [NormItemId], [Note], [StatusId], [ReportValue_ReportId], [ReportValue_NormItemId], [ControlId], [ReasonId]) VALUES (2, 167, N'Napomena test', 1, 2, 165, 1, 1)
INSERT INTO [dbo].[ReportValues] ([ReportId], [NormItemId], [Note], [StatusId], [ReportValue_ReportId], [ReportValue_NormItemId], [ControlId], [ReasonId]) VALUES (2, 168, N'Napomena test', 1, 2, 165, 1, 1)
INSERT INTO [dbo].[ReportValues] ([ReportId], [NormItemId], [Note], [StatusId], [ReportValue_ReportId], [ReportValue_NormItemId], [ControlId], [ReasonId]) VALUES (2, 169, NULL, NULL, 2, 164, NULL, NULL)
INSERT INTO [dbo].[ReportValues] ([ReportId], [NormItemId], [Note], [StatusId], [ReportValue_ReportId], [ReportValue_NormItemId], [ControlId], [ReasonId]) VALUES (2, 170, N'Napomena test', 1, 2, 169, 1, 1)
INSERT INTO [dbo].[ReportValues] ([ReportId], [NormItemId], [Note], [StatusId], [ReportValue_ReportId], [ReportValue_NormItemId], [ControlId], [ReasonId]) VALUES (2, 171, N'Napomena test', 1, 2, 169, 1, 1)
INSERT INTO [dbo].[ReportValues] ([ReportId], [NormItemId], [Note], [StatusId], [ReportValue_ReportId], [ReportValue_NormItemId], [ControlId], [ReasonId]) VALUES (2, 172, NULL, NULL, NULL, NULL, NULL, NULL)
INSERT INTO [dbo].[ReportValues] ([ReportId], [NormItemId], [Note], [StatusId], [ReportValue_ReportId], [ReportValue_NormItemId], [ControlId], [ReasonId]) VALUES (2, 173, NULL, NULL, 2, 172, NULL, NULL)
INSERT INTO [dbo].[ReportValues] ([ReportId], [NormItemId], [Note], [StatusId], [ReportValue_ReportId], [ReportValue_NormItemId], [ControlId], [ReasonId]) VALUES (2, 174, N'Napomena test', 1, 2, 173, 1, 1)
INSERT INTO [dbo].[ReportValues] ([ReportId], [NormItemId], [Note], [StatusId], [ReportValue_ReportId], [ReportValue_NormItemId], [ControlId], [ReasonId]) VALUES (2, 175, N'Napomena test', 1, 2, 173, 1, 1)
INSERT INTO [dbo].[ReportValues] ([ReportId], [NormItemId], [Note], [StatusId], [ReportValue_ReportId], [ReportValue_NormItemId], [ControlId], [ReasonId]) VALUES (2, 176, N'Napomena test', 1, 2, 173, 1, 1)
INSERT INTO [dbo].[ReportValues] ([ReportId], [NormItemId], [Note], [StatusId], [ReportValue_ReportId], [ReportValue_NormItemId], [ControlId], [ReasonId]) VALUES (2, 177, N'Napomena test', 1, 2, 173, 1, 1)
INSERT INTO [dbo].[ReportValues] ([ReportId], [NormItemId], [Note], [StatusId], [ReportValue_ReportId], [ReportValue_NormItemId], [ControlId], [ReasonId]) VALUES (2, 178, N'Napomena test', 1, 2, 173, 1, 1)
INSERT INTO [dbo].[ReportValues] ([ReportId], [NormItemId], [Note], [StatusId], [ReportValue_ReportId], [ReportValue_NormItemId], [ControlId], [ReasonId]) VALUES (2, 179, N'Napomena test', 1, 2, 173, 1, 1)
INSERT INTO [dbo].[ReportValues] ([ReportId], [NormItemId], [Note], [StatusId], [ReportValue_ReportId], [ReportValue_NormItemId], [ControlId], [ReasonId]) VALUES (2, 180, N'Napomena test', 1, 2, 173, 1, 1)
INSERT INTO [dbo].[ReportValues] ([ReportId], [NormItemId], [Note], [StatusId], [ReportValue_ReportId], [ReportValue_NormItemId], [ControlId], [ReasonId]) VALUES (2, 181, NULL, NULL, NULL, NULL, NULL, NULL)
INSERT INTO [dbo].[ReportValues] ([ReportId], [NormItemId], [Note], [StatusId], [ReportValue_ReportId], [ReportValue_NormItemId], [ControlId], [ReasonId]) VALUES (2, 182, NULL, NULL, 2, 181, NULL, NULL)
INSERT INTO [dbo].[ReportValues] ([ReportId], [NormItemId], [Note], [StatusId], [ReportValue_ReportId], [ReportValue_NormItemId], [ControlId], [ReasonId]) VALUES (2, 183, N'Napomena test', 1, 2, 182, 1, 1)
INSERT INTO [dbo].[ReportValues] ([ReportId], [NormItemId], [Note], [StatusId], [ReportValue_ReportId], [ReportValue_NormItemId], [ControlId], [ReasonId]) VALUES (2, 184, N'Napomena test', 1, 2, 182, 1, 1)
INSERT INTO [dbo].[ReportValues] ([ReportId], [NormItemId], [Note], [StatusId], [ReportValue_ReportId], [ReportValue_NormItemId], [ControlId], [ReasonId]) VALUES (2, 185, N'Napomena test', 1, 2, 182, 1, 1)
INSERT INTO [dbo].[ReportValues] ([ReportId], [NormItemId], [Note], [StatusId], [ReportValue_ReportId], [ReportValue_NormItemId], [ControlId], [ReasonId]) VALUES (2, 186, NULL, NULL, 2, 181, NULL, NULL)
INSERT INTO [dbo].[ReportValues] ([ReportId], [NormItemId], [Note], [StatusId], [ReportValue_ReportId], [ReportValue_NormItemId], [ControlId], [ReasonId]) VALUES (2, 187, N'Napomena test', 1, 2, 186, 1, 1)
INSERT INTO [dbo].[ReportValues] ([ReportId], [NormItemId], [Note], [StatusId], [ReportValue_ReportId], [ReportValue_NormItemId], [ControlId], [ReasonId]) VALUES (2, 188, NULL, NULL, NULL, NULL, NULL, NULL)
INSERT INTO [dbo].[ReportValues] ([ReportId], [NormItemId], [Note], [StatusId], [ReportValue_ReportId], [ReportValue_NormItemId], [ControlId], [ReasonId]) VALUES (2, 189, NULL, NULL, 2, 188, NULL, NULL)
INSERT INTO [dbo].[ReportValues] ([ReportId], [NormItemId], [Note], [StatusId], [ReportValue_ReportId], [ReportValue_NormItemId], [ControlId], [ReasonId]) VALUES (2, 190, N'Napomena test', 1, 2, 189, 1, 1)
INSERT INTO [dbo].[ReportValues] ([ReportId], [NormItemId], [Note], [StatusId], [ReportValue_ReportId], [ReportValue_NormItemId], [ControlId], [ReasonId]) VALUES (2, 191, N'Napomena test', 1, 2, 189, 1, 1)
INSERT INTO [dbo].[ReportValues] ([ReportId], [NormItemId], [Note], [StatusId], [ReportValue_ReportId], [ReportValue_NormItemId], [ControlId], [ReasonId]) VALUES (2, 192, N'Napomena test', 1, 2, 189, 1, 1)
INSERT INTO [dbo].[ReportValues] ([ReportId], [NormItemId], [Note], [StatusId], [ReportValue_ReportId], [ReportValue_NormItemId], [ControlId], [ReasonId]) VALUES (2, 193, N'Napomena test', 1, 2, 189, 1, 1)
INSERT INTO [dbo].[ReportValues] ([ReportId], [NormItemId], [Note], [StatusId], [ReportValue_ReportId], [ReportValue_NormItemId], [ControlId], [ReasonId]) VALUES (2, 194, N'Napomena test', 1, 2, 189, 1, 1)
INSERT INTO [dbo].[ReportValues] ([ReportId], [NormItemId], [Note], [StatusId], [ReportValue_ReportId], [ReportValue_NormItemId], [ControlId], [ReasonId]) VALUES (2, 195, NULL, NULL, 2, 188, NULL, NULL)
INSERT INTO [dbo].[ReportValues] ([ReportId], [NormItemId], [Note], [StatusId], [ReportValue_ReportId], [ReportValue_NormItemId], [ControlId], [ReasonId]) VALUES (2, 196, N'Napomena test', 1, 2, 195, 1, 1)
INSERT INTO [dbo].[ReportValues] ([ReportId], [NormItemId], [Note], [StatusId], [ReportValue_ReportId], [ReportValue_NormItemId], [ControlId], [ReasonId]) VALUES (2, 197, N'Napomena test', 1, 2, 195, 1, 1)
INSERT INTO [dbo].[ReportValues] ([ReportId], [NormItemId], [Note], [StatusId], [ReportValue_ReportId], [ReportValue_NormItemId], [ControlId], [ReasonId]) VALUES (2, 198, N'Napomena test', 1, 2, 195, 1, 1)
");
            Sql(@"SET IDENTITY_INSERT [dbo].[Users] ON
INSERT INTO [dbo].[Users] ([UserId], [Email], [Password], [Name], [LastName], [JMBAG], [Created], [Modified], [OrganisationId], [IsActive], [IsOrganisationLeader]) VALUES (1, N'tnovak@vvg.hr', N'Mw--', N'Tom', N'N', 123456, N'2018-10-15 21:47:06', NULL, 1, 1, 1)
INSERT INTO [dbo].[Users] ([UserId], [Email], [Password], [Name], [LastName], [JMBAG], [Created], [Modified], [OrganisationId], [IsActive], [IsOrganisationLeader]) VALUES (2, N'jpavlov@vvg.hr', N'Mw--', N'J', N'Lo', 123456, N'2018-10-15 21:47:06', NULL, 1, 1, 0)
INSERT INTO [dbo].[Users] ([UserId], [Email], [Password], [Name], [LastName], [JMBAG], [Created], [Modified], [OrganisationId], [IsActive], [IsOrganisationLeader]) VALUES (3, N'test@vvg.hr', N'Mw--', N'Test', N'Testi?', 123456, N'2018-10-15 21:47:06', NULL, 2, 1, 1)
INSERT INTO [dbo].[Users] ([UserId], [Email], [Password], [Name], [LastName], [JMBAG], [Created], [Modified], [OrganisationId], [IsActive], [IsOrganisationLeader]) VALUES (4, N'test2@vvg.hr', N'Mw--', N'Test22', N'Testi?2', 123456, N'2018-10-15 21:47:06', NULL, NULL, 1, 0)
INSERT INTO [dbo].[Users] ([UserId], [Email], [Password], [Name], [LastName], [JMBAG], [Created], [Modified], [OrganisationId], [IsActive], [IsOrganisationLeader]) VALUES (5, N'test3@vvg.hr', N'Mw--', N'Test33', N'Testi?3', 123456, N'2018-10-15 21:47:06', NULL, NULL, 1, 0)
INSERT INTO [dbo].[Users] ([UserId], [Email], [Password], [Name], [LastName], [JMBAG], [Created], [Modified], [OrganisationId], [IsActive], [IsOrganisationLeader]) VALUES (6, N'isti@vvg.hr', N'Mw--', N'Testko', N'Testi?i?', 123456, N'2018-10-15 21:47:06', NULL, NULL, 0, 0)
SET IDENTITY_INSERT [dbo].[Users] OFF
");
            Sql(@"INSERT INTO [dbo].[UserRoles] ([UserId], [RoleId]) VALUES (1, 1)
INSERT INTO [dbo].[UserRoles] ([UserId], [RoleId]) VALUES (2, 2)
");
        }

        public override void Down()
        {
        }
    }
}
